### ISSUE TITLE
Crafting Lists: Hide "Done" rows

### ISSUE THREAD

**Issue by filliph** [Critical-Impact/InventoryTools#111]
**Is your feature request related to a problem? Please describe.**
For very large crafting lists, showing all "Done" rows is not necessarily helpful and can lead to a lot of scrolling to find the items that are still to-do.

**Describe the solution you'd like**
Checkbox next to "Highlight" for whether to hide or show "Done" rows.

**Comment by Critical-Impact** [comment]
Available in the latest version.
