### ISSUE TITLE
Crafting Lists: Highlight only pre-crafts

### ISSUE THREAD

**Issue by filliph** [Critical-Impact/InventoryTools#114]
**Is your feature request related to a problem? Please describe.**
When moving items out of a retainer, it's not always helpful to show both pre-craft and ingredients. For instance, let's say I need Bronze Ingots, but I also have Copper Ore and Tin Ore. The current system would show that I need to move all 3 items, when in reality only the Bronze Ingots are needed.

**Describe the solution you'd like**
Add a checkbox next to the "Highlight" box that said "Only Pre-crafts". Ticking this box would highlight only pre-craft items in inventories.

**Additional context**
Another reason for this is that due to opportunity cost, it's often better to simply buy the pre-craft items off the Market Board. Hiding ingredients will help with only purchasing what's necessary.

**Comment by Critical-Impact** [comment]
The crafting update will account for this.
It'll will only ask you to retrieve the exact amount you need taking into account precrafts. It also lets you choose to forgoe retrieval at all if you wish and source entirely from the MB for specific items.
