### ISSUE TITLE
Pressing "Down" on crafting list order can crash AT

### ISSUE THREAD

**Issue by filliph** [Critical-Impact/InventoryTools#116]
**Describe the bug**
If a crafting list has an order of 1 and you press the Down button, Allagan Tools will pop up a window saying it encountered an error and that I should restart the game.

**To Reproduce**
1. Open `/atconfig` interface
2. Press "Down" on the remaining list when its order is 1
3. See error

**Expected behavior**
Either the button to disappear or for nothing to happen when you click it.

**Dalamud Information:**
Testing is not enabled.

**Additional context**
This only occurs when you have only one crafting list.

**Comment by Critical-Impact** [comment]
Should not be happening in the latest version.
