### ISSUE TITLE
Right click -> Add to crafting list opens wrong UI

### ISSUE THREAD

**Issue by filliph** [Critical-Impact/InventoryTools#117]
**Describe the bug**
When viewing a filter and you right click -> Add to crafting list, it opens the crafting list config UI (`/crafts`) rather than the crafting list itself.

**To Reproduce**
1. Open "All Game Items" or similar
2. Right click on a craftable item and Add to crafting list
3. The wrong UI will open

**Expected behavior**
The crafting list itself to be opened in a new window.

**Dalamud Information:**
Testing is not enabled.

**Comment by Critical-Impact** [comment]
This should work correctly now. The configuration UI and craft list UI are basically the same window but it should switch to the correct mode and tab/select the correct filter.
