### ISSUE TITLE
Crafting lists don't update when crafting

### ISSUE THREAD

**Issue by filliph** [Critical-Impact/InventoryTools#118]
**Describe the bug**
When crafting an item, the number required is not updated in the "To Craft" block.

**To Reproduce**
1. Add an item to crafting list
2. Craft it
3. "Required" count does not decrease / item is not removed from the list when all requirements are met

**Expected behavior**
The "Required" count to decrease and/or the item to be removed when the required number of crafts are completed.

**Screenshot**
This happened after crafting 1 item:
![image](https://user-images.githubusercontent.com/9424286/185797974-4f31a66f-bdc8-4eba-906d-b539cbbf04a2.png)

**Dalamud Information:**
Testing is not enabled. Multi-monitor windows is enabled.

**Additional context**
The "Pre-craft" block _does_ update correctly, just not the main crafting block. I tried sorting my inventory and manually shifting item locations to force an update, but this did not work.

**Comment by filliph** [comment]
I had problems with autofill from gathering too. I tried to replicate it by turning off the multi-monitor windows, closing the game, relaunching (autofill worked again), turning multi-monitor on again, closing the game, relaunching (autofill still works).

At the time of writing I don't know the trigger for it breaking. If I manage to narrow it down, I'll update the OP and also add it in a comment.

**Comment by Critical-Impact** [comment]
"Highlight?" needs to be checked on when crafting. I will admit this is not ideal and I do plan on adding something that lets you pick which craft list you are currently tracking against.
