### ISSUE TITLE
Better UX for opening and deleting a crafting list

### ISSUE THREAD

**Issue by filliph** [Critical-Impact/InventoryTools#119]
**Is your feature request related to a problem? Please describe.**
Right now, the way to open a crafting list is not very intuitive. You have to use `/atconfig`, then click "Craft Lists", then click "Open as Window".

Similarly, you have to go to the same page to delete a crafting list.

**Describe the solution you'd like**
The "Open as window" and "Remove" buttons to also exist somewhere in the `/crafts` interface.

**Describe alternatives you've considered**
Right clicking the list name in the `/crafts` window could also be a valid solution to show those buttons, if there's no suitable locations for them.

**Comment by wirchtalksgames** [comment]
I agree with the part about deleting crafting lists. However, the /crafts command opens up the crafting lists directly for me; I don't quite follow what you're describing here!

Pic is what I get when using /crafts

![image](https://user-images.githubusercontent.com/43225296/185794964-fb3ac41c-a4bd-46f9-ac9d-7acae7ed8ec7.png)

**Comment by filliph** [comment]
@wirchtalksgames this issue is related to #115 

I also don't see the config icon you're seeing:
![image](https://user-images.githubusercontent.com/9424286/185795361-8b9ae688-a59d-4b84-b2dc-59f5a8e7df7d.png)
If relevant, I have my UI scaled to 150% in FFXIV's config because I run a 1440p monitor and I'm also old and blind.

If the little gray blob is meant to be a config icon, then that changes both this issue and #115 as there would indeed be a way to access the config 😄

**Comment by wirchtalksgames** [comment]
It is indeed a config button, but I don't know why it's not showing in yours. I took a look at my config and there doesn't seem to be any options related to the display of the config button in the crafting list.

**Comment by filliph** [comment]
It's probably a scaling issue then, presumably you're running at 100%?

I run 125% in Windows and 150% in XIV (why no 125% in XIV, Square!?), you young'uns and your good eyesight, back in my day I tells ya...

**Comment by wirchtalksgames** [comment]
Afaik, dalamud components are independent from the game's settings. If i set my scale to 150%, the dalamud windows remain untouched. I just tried it out and I still see the config button on my crafting lists at 150%. 

And don't worry, I'm blind af too—my prescription glasses are as thick as an Eulmorean noble.
