### ISSUE TITLE
Crafting list UI improvements

### ISSUE THREAD

**Issue by filliph** [Critical-Impact/InventoryTools#120]
**Is your feature request related to a problem? Please describe.**
None of the blocks ("To Craft", "Precrafts" etc) inside the crafting list are collapsible.

**Describe the solution you'd like**
The "To Craft", "Precrafts" etc blocks should also be collapsible, since this would allow us to see at a glance the pre-craft items we can buy from the Market Board / from NPC vendors without also seeing a bunch of ingredients that may or may not be required.

**Additional Context**
See #125

**Comment by wirchtalksgames** [comment]
I agree with this, but I added a ticket about alternate item layouts that I think you might be interested in. Maybe you could take a look and give your insights there? I also opened another ticket for table resizing when collapsed, so feel free to leave it a like so it can get prioritized!

**Comment by filliph** [comment]
I'll edit this ticket to remove the collapse stuff, your ticket can be the canonical one for that 🙂

**Comment by Critical-Impact** [comment]
Closing this as this is the actual behaviour in the live version.
I do appreciate the tickets and I will be taking the comments from #124 on board when I work on the crafting improvements
