### ISSUE TITLE
Market board purchases don't update the list until sort

### ISSUE THREAD

**Issue by filliph** [Critical-Impact/InventoryTools#122]
**Describe the bug**
When you purchase an item off the market board, the crafting list does not update until you sort your inventory.

**To Reproduce**
1. Open a crafting list
2. Purchase an ingredient or pre-craft off the Market Board
3. Notice the list does not update
4. Sort inventory
5. List updates

**Expected behavior**
List to be updated immediately upon purchase.

**Dalamud Information:**
Testing is not enabled.

**Comment by Critical-Impact** [comment]
Let me know if this is still an issue, as far as I know in the latest version any item coming into the inventory should fire off a filter change.
