### ISSUE TITLE
Crafting Lists: Show all NPC buyable items in a separate grouped list

### ISSUE THREAD

**Issue by filliph** [Critical-Impact/InventoryTools#123]
**Is your feature request related to a problem? Please describe.**
When working with a large crafting list, sometimes you need to buy multiple different items from multiple different vendors. Currently, there is no way of seeing a grouped list of all NPCs you need to buy items from, and what items you need to buy.

For instance, let's say you need to buy both Iron Ingots and Iron Rivets from the Amal'jaa vendor; currently those two items can be in wildly different locations in the overall crafting list.

**Describe the solution you'd like**
A "Show NPC vendors" button inside a crafting list that shows a grouped list of all NPC vendors, and the items they sell that you need.

**Comment by Critical-Impact** [comment]
This is implemented in the latest version, items can be grouped by zone along with the ability to prefer specific zones(which will auto pick vendors in those zone)
