### ISSUE TITLE
Make the tables within a crafting list take up more space if another table is collapsed, in order to optimize space and improve overall data presentation.

### ISSUE THREAD

**Issue by wirchtalksgames** [Critical-Impact/InventoryTools#125]
**Is your feature request related to a problem? Please describe.**
Whenever you collapse a table within a crafting list, there's a bunch of empty space remaining where the expanded table would be. This is frustrating since there's really no point to, for example, keeping the retainer table open once you've extracted the corresponding items from your retainers, and there is a bunch of wasted space in the crafting list if you collapse it.

**Describe the solution you'd like**
Make the craft/gatherable/precraft table expand to take up more space if the retainer table is collapsed

![ffxiv_dx11_AP1S3gTKq7](https://user-images.githubusercontent.com/43225296/185794023-de1df637-e504-4985-a36e-546bb2dd9c60.png)

**Comment by Critical-Impact** [comment]
This is implemented so I'm closing however I am aware that the UI within the craft window is not ideal.
I've got some changes in the work but imgui is starting to get in the way of the more complex UI I was envisioning
