### ISSUE TITLE
Clicking on desynthesizable items in the "acquisition" column doesn't open additional information panels

### ISSUE THREAD

**Issue by wirchtalksgames** [Critical-Impact/InventoryTools#126]
**Describe the bug**
Unlike the items in the other filters that you can left click on to open a panel with additional information, including integration with gatherbuddy to tp to the gather location, the items that are listed in the "acquisition" column don't actually work in the same way. 

**To Reproduce**
1. Open any crafting list with items in it
2. If an item is acquired via desynth, such as "dawnborne aethersand", you will see the items that you can desynth to get in in the "acquisition" column
3. Clicking on these items should open the information panel where you can check where to gather desynth items.
4. Information panel doesn't open.

**Expected behavior**
The information panel should open when you click on these items so you could check more info, or tp to the gathering location via gatherbuddy. This works on any items in the filters, but not for the items listed in the acquisitions column. I don't know if this is a bug, or if it's just a missing feature. Apologies if I listed it under the wrong category.

**Screenshots**

![image](https://user-images.githubusercontent.com/43225296/185813507-a4581382-e145-44be-a890-992ff0a42ffc.png)

When you click on the highlighted items, the information panel doesn't open.

**Dalamud Information:**
I have testing enabled.

**Comment by Critical-Impact** [comment]
This is fixed in the latest version, closing
