### ISSUE TITLE
Add "Required" items column in the retainer table

### ISSUE THREAD

**Issue by wirchtalksgames** [Critical-Impact/InventoryTools#129]
**Is your feature request related to a problem? Please describe.**
Whenever we're extracting materials that we already had in the retainer, we have to manually search for the required amount on the "To Craft" table, adding an extra verification step to the process.

**Describe the solution you'd like**
Add a "Required" column to the retainer table, just like in the "To Craft" table.

![image](https://user-images.githubusercontent.com/43225296/185827718-3a4098b9-2985-4504-9b43-1ee028258ab2.png)

**Comment by Critical-Impact** [comment]
Implemented, will be in next release.
I'm also adding tooltip functionality so you can see how much you should retrieve from a retainer when you hover over an item.
