### ISSUE TITLE
AT does not count HQ items in your inventory towards the "available items" column.

### ISSUE THREAD

**Issue by wirchtalksgames** [Critical-Impact/InventoryTools#130]
**Describe the bug**
While AT counts HQ items towards the items in your "inventory" column, it doesn't reflect them in the "quantity available" column. Furthermore, even if you already have sufficient materials (by combining the NQ and HQ items in your inventory) the mod will still show a number of items in the "craftable" sections, as if you're missing them.

**To Reproduce**
1. Start a crafting list and begin crafting pre-crafts
2. When you get an HQ variant of a pre-craft, you'll see it count towards your "inventory" total, but not in the "quantity available" column
3. Further, the "craftable" column also shows a number of craftable items, as if you're still missing some of them.

**Expected behavior**
The plugin should count the combined values of NQ and HQ pre-craft items towards the total, and this should reflect both in the "quantity available" and "craftable" columns. If you have enough pre-crafts of a certain item, the "craftable" should be 0, and the "available" items should be the same as the "required" (considering that you have the exact amount of items in your inventory)

**Screenshots**
![image](https://user-images.githubusercontent.com/43225296/186792867-05d9c5f8-815e-40f7-917b-1fb123950c83.png)

**Dalamud Information:**
Yes

**Comment by devmpg** [comment]
Current workaround I found is to remove the items from the to craft group as I make them

**Comment by Critical-Impact** [comment]
NQ/HQ handling should be far improved in the latest release
