### ISSUE TITLE
Show the no. of items presently in a search/filter

### ISSUE THREAD

**Issue by SkepticSpoon** [Critical-Impact/InventoryTools#131]
**Is your feature request related to a problem? Please describe.**
Right now there's no way to know how many items a given filter has nor how that number changes with further filtering

**Describe the solution you'd like**
I would like for the filters to show, maybe in the bottom (next to the "Pending Market Requests" or next to the help/craft/settings icons) how many items correspond to the current filter, and for that number to change if we apply further filters/options to the columns

**Describe alternatives you've considered**
-

**Additional context**
An example of this might be what the ItemSearch plugin does, where it shows the current number of items that correspond to the search conditions, and that number live updates while we change the search conditions (can't take a SS at the moment because it has not yet been updated for 6.2)

**Comment by Critical-Impact** [comment]
Available in the latest version
