### ISSUE TITLE
Filters for "Is it Dyeable?" and "Is it mogstation?"

### ISSUE THREAD

**Issue by SkepticSpoon** [Critical-Impact/InventoryTools#132]
**Is your feature request related to a problem? Please describe.**
When I'm searching for gear in Allagan Tools I'd like to be able to filter the gear/glamour based on it being dyeable. It would also be useful to be able to filter for gear/glamour that is from the mogstation

**Describe the solution you'd like**
2 new columns - one that says if the gear is dyeable (could also be applied to furniture, I guess) and another for gear that is buyable through mogstation (maybe could also be applied to other items as well)

**Describe alternatives you've considered**
-

**Additional context**
Regarding the mogstation filter, ItemSearch has an option in the settings that toggles the ability to get info on what items are on the mogstation in order for the filter to work. Maybe that helps in how this could be achieved

**Comment by Critical-Impact** [comment]
So I've added in a dyeable filter but ItemSearch actually pings the mogstation site to determine what items are available. Ideally I'd like as few external sources of data as possible. I'll investigate something to do the data scraping on my end and then package it into the plugin.
Will add a ticket over on LuminaSupplemental to parse this data.
