### ISSUE TITLE
"Aquisition" column - show if it's a duty drop and the name of the duty it drops from

### ISSUE THREAD

**Issue by SkepticSpoon** [Critical-Impact/InventoryTools#135]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
The "Aquisition" column maybe could show if an item is a drop from a duty and in the tooltip from which duty/duties it drops from, similar to what is done for treasure maps drops. Additionally, if feasible, maybe it would be useful to also show which items are mob drops with a tooltip showing which mobs (and also coords?) they drop from

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Critical-Impact** [comment]
Hi, this is partially available.
The duty data is manually sourced from GT's data store.
The mob drop data is sourced from a few different places.
Mob spawn data is available but it requires people to turn on "Track Mob Spawns" in their settings and run around the various zones to collect the data. Once they've collected say a months worth of data they can submit it to me and I can merge it into the latest AT.

I'll close this for now but if you have any suggestions about how the duty/mob data could be displayed better feel free to open another issue.
