### ISSUE TITLE
Items don't reflect in crafting list when added through the "Craftable - Add to Craft List" button in the information panel.

### ISSUE THREAD

**Issue by wirchtalksgames** [Critical-Impact/InventoryTools#136]
**Describe the bug**
As the title says, items that are added through crafting lists through the corresponding button the info panel don't reflect on the list itself. However, when you add the item by right clicking them in any inventory tab, the item will appear on the crafting list, along with the the first item that was seemingly never added.

**To Reproduce**
1. Create a crafting list.
2. Go to any AT inventory filter tab, and click on any craftable item to open the information panel.
3. Click on the "Craftable - Add to Craft List" in the info panel, and choose to add it to the crafting list.
4. The item should appear on the list, but it doesn't.
5. Go back to the AT inventory filter tab, and try adding the item again, but through right click > "Add to Craft List - XXX"
6. The item should now correctly show on the list, but with the additional item you tried adding first, that seemingly didn't work.

**Expected behavior**
Items should be added to the crafting list without issue, regardless on from WHERE you added them.

**Screenshots**

[ffxiv_dx11_eNgJDLaDxT.webm](https://user-images.githubusercontent.com/43225296/187010827-be0bb318-2bba-4044-832c-a15e7546c430.webm)

**Dalamud Information:**
Yes

**Comment by wirchtalksgames** [comment]
Excuse the lack of mouse cursor on the video, but hopefully the circle highlight can help you identify the issue i'm describing

**Comment by Critical-Impact** [comment]
This should be sorted in the latest version. Let me know if you run into any problems
