### ISSUE TITLE
Lag when looting an item

### ISSUE THREAD

**Issue by drejjmit** [Critical-Impact/InventoryTools#142]
**Describe the bug**
Each time i loot an item i get a ~60ms lag spike

**To Reproduce**
Easiest to notice is if you're 'Quick Synthesis' 99 items. Each item received triggers a 50-70ms lag spike

**Screenshots**
![image](https://user-images.githubusercontent.com/15526476/187781547-02bbd929-280b-466a-b7e8-f672e2b3aa1b.png)

When i stop looting / crafting, the lag is gone
![image](https://user-images.githubusercontent.com/15526476/187782560-ac3fc3f7-c17a-40cc-aadb-31b53b336b22.png)

Version 1.2.0.3

**Comment by drejjmit** [comment]
Just interacting with anything seems to makes the ``InventoryMonitor::FrameworkOnUpdate`` cause a framespike. 
I just interacted with a ``Oasis Flowerpot`` in my estate and it shot up to 220ms from just clicking it. 
No items were looted.
![image](https://user-images.githubusercontent.com/15526476/187911201-64a203b7-248b-4acd-9b75-2bc6a755b60b.png)

**Comment by Critical-Impact** [comment]
I'm aware, I'm honestly not sure at this point, I'm still investigating but I'm finding it very difficult to replicate consistently.

**Comment by drejjmit** [comment]
Must be in the Lib. I get the same lag when only using ``InventorySearchBar`` that uses your CriticalCommonLib
<https://github.com/Tischel/InventorySearchBar>

**Comment by Critical-Impact** [comment]
Can you let me know if the issue is still a problem in the latest release? Have done what I can to make the scanning process run outside of the game's main update loop.

**Comment by drejjmit** [comment]
Much better now. Thank you. I'll make a new/reopen this issue if i notice anything.
