### ISSUE TITLE
Highlight Tooltip Window overlap/stuck open

### ISSUE THREAD

**Issue by RaikuNara** [Critical-Impact/InventoryTools#143]
**Describe the bug**
When item is hovered over with a mouse to open tooltip item Allagan Tools item more information window opens and does not close. It also rapidly flickers. Is there a way to disable this feature?

**To Reproduce**
Go to inventory -> Hover over items

**Expected behavior**
Before 6.2 this tooltip window closed when no longer hovering over item

![Tooltip](https://user-images.githubusercontent.com/112778651/188284966-3f6cbf1b-e8b4-46c6-ae85-6de21be55bac.png)

**Comment by Critical-Impact** [comment]
Sorry, thought I had fixed that, go into settings and set a hotkey for the "More Information" hotkey and it should stop happening.

**Comment by RaikuNara** [comment]
Resolved. Thank you so much! Fantastic plugin btw 10/10 :)
