### ISSUE TITLE
Craft List: Item quantity not reflected in table upon buying from tomestones

### ISSUE THREAD

**Issue by Vyling** [Critical-Impact/InventoryTools#146]
**Describe the bug**
I had the Craft List open with mats to get for crafting new Gatherer Gear. I saw that I needed to buy some for tomestones, so I went to Cihanti in Radz-At-Han. After buying any of the four bottom materials, I didn't notice any change in the Craft List. 

**To Reproduce**
1. Have a crafting list with materials that can be bought for tomestones
1. Go to Radz-at-Han ( 10.8, 10.3 )
2. Talk with Cihanti
3. Choose option for Astronomy (others)
4. Buy any material 
5. Table doesn't update

**Expected behavior**
I'd expect the "Quantity Available" to go up and "Missing" to go down.

**Screenshots**
Besitz = owning
![image](https://user-images.githubusercontent.com/30179258/188331566-00d994d4-06a1-41ff-b00b-1bfa5bb28699.png)

**Dalamud Information:**
Do you have testing enabled? <- Yes

**Additional context**
 Nothing showing in /xllog

If you need more infor

**Comment by Critical-Impact** [comment]
This is fixed in the latest version, any inventory change should be automatically picked up(retainer/FC chest, any inventory that relies on network data coming in being the exception)
