### ISSUE TITLE
Show required # of currency

### ISSUE THREAD

**Issue by Vyling** [Critical-Impact/InventoryTools#148]
**Is your feature request related to a problem? Please describe.**
When looking at my craft list, I was wondering how many Allagan Tomestones I'd need to buy all the required mats. Same with bicolored gemstones, or how many gather/crafter scrips I'd need to collect to have enough for the missing amount of materials.

**Describe the solution you'd like**
It would be nice if it would show the exact number of required currency for the item in the Craft List. Either on hover or below the picture, going by the missing amount of items.

**Describe alternatives you've considered**
Teleporting and seeing how much one of the mats costs and adding it all up and writing it down myself. 
Or using Teamcraft instead.

**Additional context**
I might not have listed all currencies. 
If you have any further concerns or questions, feel free to comment.

**Comment by Critical-Impact** [comment]
Implemented in the latest version, you can pick how you want to source an item including seals, tokens, etc
