### ISSUE TITLE
question/request. permanently pre-change newly made list inventory settings?

### ISSUE THREAD

**Issue by Rayna-Grimm** [Critical-Impact/InventoryTools#152]
**Is your feature request related to a problem? Please describe.**
/Crafts: every time i make a new list i have to go through and re-do its inventories settings so i can see the items my alts and their retainers have. 

**Describe the solution you'd like**
would be helpful if there were settings in the configuration menu for /crafts that permanently made it so all the general>inventories settings were already set how i prefer them to stay set when the list is made instead of having to re-do it every. single. time.

also if this is already possible could someone just tell me how to do it? I've looked through the settings and the wiki here so if its possible i was unable to figure out how to set it up alone sadly, sorry, 

edit: thanks for the still petty amazing plugin, i know these projects often only get better with time(and the devs hard work of course!)

**Additional context**
i have a solo FC with my alts and use the FC chest to trade between them so the alts are item mules. so it would be extra helpful if i didnt have to constantly change all the settings and tags each time a new list is made, unfortunately its becoming tedious to have to change 4-6 things to yes, then re-add all the different types of inventory categories each time i make a new crafting list

**Comment by Critical-Impact** [comment]
Not possible yet, have this added in the new version though, unsure when it will come out, probably a week or two.
