### ISSUE TITLE
[Suggestion] Better FC Chest handling cross-characters for characters sharing an FC

### ISSUE THREAD

**Issue by Phenrei** [Critical-Impact/InventoryTools#159]
I have a solo FC with a company chest I use to transfer items. Right now in AT, the FC chest contents are stored per-character and if one character opens the chest the last quantity they saw is forever added to the totals, causing duplicates or even more if I don't clear their inventory histories or revisit the chest. If there is a way to exclude FC chest inventory from the tooltips from specific characters this may solve the issue, though if this currently exists I was not able to determine how. But ultimately if an FC chest is being tracked, remembering the FC name of the character and keeping only the most recent data for said chest if it is visited by another character would be a more permanent solution.

**Comment by Critical-Impact** [comment]
This is now available in the latest live version. FCs have their own unique ID and as such should only show up once even if you access them across multiple characters.

Please open a new issue if you do run into problems using the new functionality.
