### ISSUE TITLE
Add the ability to create Crafting Lists directly from item filters

### ISSUE THREAD

**Issue by wirchtalksgames** [Critical-Impact/InventoryTools#161]
**Is your feature request related to a problem? Please describe.**
When looking to craft items, you always need to manually create a crafting list before being able to add them, which is inconvenient since item filters and craft lists are in different menus.

**Describe the solution you'd like**
When right clicking an item within an AT filter, you should be able to add the selected item to a new crafting list, and the plugin should be able to create it automatically, in case there isn't a crafting list available already. This could also help if you have multiple crafting lists already created, but want to add the item to a separate list as a one-time quick craft, such as when you're quickly updating your gear for a new class.

**Comment by Critical-Impact** [comment]
Available on the latest version
