### ISSUE TITLE
Inventories not updating

### ISSUE THREAD

**Issue by SumiMochi** [Critical-Impact/InventoryTools#162]
Noticed the other day that my inventories don't always update. If I close and relaunch the game the inventory will usually update but then not update if any changes happen after. 
Using testing version 1.2.0.8

**Dalamud Information:**
Testing Enabled

**Comment by Critical-Impact** [comment]
Which inventories specifically? If it's retainer it's a known issue and I am in the process of debugging it.

**Comment by SumiMochi** [comment]
It seems to be across all of my inventories.  Here are a couple of photos, the endwood aethersand is in my regular inventory and hasn't updated since a couple days ago. The endstone I had just moved to my saddle bag and the location didn't update. This happens with other items too, if their quantity changes or they get moved to a different inventory they aren't updating.
Let me know if more information will help. Thanks.


![Inventory](https://user-images.githubusercontent.com/115683822/195733715-483dd81a-134c-4305-b32f-6c440e9fc9f2.png)
![Inventory2](https://user-images.githubusercontent.com/115683822/195733717-c4bee23f-daf3-4092-90cd-6d4d43ca4c54.png)

**Comment by Critical-Impact** [comment]
Could you do me a favour and open /xllog, using the gear icon set it to "debug"
Move some items around then send me your dalamud.log?
dalamud.log can be found in %AppData%\XIVLauncher
Feel free to send it to me via Critical_Impact#4884 on discord, otherwise you could post it here

**Comment by Critical-Impact** [comment]
Should be working in the latest version, let me know if it's not and I can reopen.
