### ISSUE TITLE
Define 'Next Step' for multiple sources

### ISSUE THREAD

**Issue by grizzilk-codes** [Critical-Impact/InventoryTools#163]
**Is your feature request related to a problem? Please describe.**
When using the crafts page, there appears to be no way to tell it how you want to acquire an item. For example, Iron Ore can be acquired through mining or vendor. However, the crafts page will tell you to gather it if it's needed.

**Describe the solution you'd like**
Ideally, there would be a way to turn "Next Step" from "Gather 10" to "Buy 10" or instead of "Buy 20" you can tell it you would like to craft an item, for example Steel ingots.

**Additional context**
This is most notable for alts or players who do not have all tribes unlocked. So when a craft requires a Steel Ingot, it tells you to buy some from the Amalja, but there appears to be no way to disable this.

**Comment by Critical-Impact** [comment]
This is fully implemented in the latest version, while it is not dynamic in the sense that it knows what level/tribes you have unlocked, it is possible to pick how you wish to source an item.
