### ISSUE TITLE
Tooltip: Option to only show which retainer/character has the item, and the amount

### ISSUE THREAD

**Issue by liamont** [Critical-Impact/InventoryTools#164]
Currently if the user wishes to see which retainer/character has what item in the tooltip, it shows up with all the locations of the item. If there are many copies of the item in question, the list becomes very long and clips off the screen like so: 

![screenshot](https://i.imgur.com/CllLnig.png)

If there could be an option to limit the tooltip to only show the retainer/character with amount, and in which inventory it is, that would be great. 

For example, using the above screenshot:

> Retainer A (Character A) - Bag (12) (NQ)
> Retainer B (Character A) - Market (5) (NQ)
> ...

**Comment by Critical-Impact** [comment]
The tooltip settings now provide multiple ways to display the items along with limits on the maximum amount of items shown.
There are probably a few more improvements I will make but I'm closing this as I think the current settings available should cover what has been requested in this issue.
