### ISSUE TITLE
Options for improved NQ/HQ display

### ISSUE THREAD

**Issue by Elypha** [Critical-Impact/InventoryTools#166]
**Is your feature request related to a problem? Please describe.**
a) The NQ/HQ indicator at the end of the tooltips can sometimes be hard to identify
![image](https://user-images.githubusercontent.com/30290883/198126177-215996bc-7962-4dd9-a3f8-66a4a40ff61b.png)
b) Some items in game do not have HQ variant at all
![image](https://user-images.githubusercontent.com/30290883/198127051-d20e045f-7be1-49e6-99c9-13148b81e027.png)

**Describe the solution you'd like**
It would be great to have an option to toggle the way NQ/HQ is displayed. For example, 
- Leave it blank for NQ items, and `(HQ)` for HQ items. 
	- Or, maybe it could be even better to display the HQ icon for HQ items instead of the text of HQ
- In addition, the solution raised in #164 can also be helpful to my problem.

**Comment by Critical-Impact** [comment]
Items now have the HQ icon next to them to indicate as such. NQ items have nothing.
There's been quite a few improvements to the customisation available with tooltips, hopefully that makes it clearer :)
