### ISSUE TITLE
Have a limit on how many entries are shown in Tooltip?

### ISSUE THREAD

**Issue by drejjmit** [Critical-Impact/InventoryTools#169]
The whole UI flickers each time i hover over an item where InventoryTools is trying to add 200 lines to the tooltip. 
Maybe limit it to 10 or something?
![image](https://user-images.githubusercontent.com/15526476/202492578-8b04b9df-c98d-4d64-bd31-45bd41beffc8.png)

**Comment by Critical-Impact** [comment]
There is a limit now available(with the default being 10) for items shown in tooltips.
Closing this
