### ISSUE TITLE
Are free company chests tracked anymore?

### ISSUE THREAD

**Issue by KKConrad** [Critical-Impact/InventoryTools#170]
Title says all. Was it removed?

**Comment by drejjmit** [comment]
There's something fishy after latest client update. Items are sometimes not tracked in bags either.

This for example. I clearly have it in my bag, yet it's only showing that i have it in my retainer
![image](https://user-images.githubusercontent.com/15526476/202853542-fec9d063-5f9e-44a3-93f3-d80895bc5cc2.png)

I see the same pattern with **Inventory Search Bar** not highlighting/finding items that i clearly have in my bags

Both plugins are using **CriticalCommonLib**

**Comment by Critical-Impact** [comment]
This should be fixed now, we are using hooks instead of opcodes so it should work every patch barring a hook being out of place.
