### ISSUE TITLE
L2/Ctrl FPS Drops

### ISSUE THREAD

**Issue by mikazuki4649** [Critical-Impact/InventoryTools#171]
Hi there! I've been struggling with this for months until someone pointed out to me that it could be this plugin. So the issue from #33 seems like it's still happening, I've been experiencing this ever since 6.2 updates rolled out a few months ago. Could you please help take a look it please? I love the convenience of this plugin so I would love to keep using it.

**Comment by Critical-Impact** [comment]
The latest version, do you still get the same issue?

**Comment by NCC-Lykos** [comment]
I'm getting progressive frame drops as I play, I disabled this addon and my frame rate shoots back up to normal. I can toggle the addon to tank my FPS and then bring it back up....

**Comment by Critical-Impact** [comment]
What version are you on?
Is it only when you are looking at a tooltip of an item specifically?

**Comment by NCC-Lykos** [comment]
> What version are you on? Is it only when you are looking at a tooltip of an item specifically?

I just installed the latest update 1.2.0.17 and it was good for a minute, but now the FPS is dropping rapidly. I disable the plugin and it pops right back to 60

**Comment by Critical-Impact** [comment]
Hmm definitely a tough one to track down, can you send through your InventoryTools.json which should be available in
C:\Users\YourUserName\AppData\Roaming\XIVLauncher\pluginConfigs

Also are you using a controller at all?

**Comment by NCC-Lykos** [comment]
> 

No controller.

I just had the issue again on latest update.

[InventoryTools.zip](https://github.com/Critical-Impact/InventoryTools/files/10711191/InventoryTools.zip)

**Comment by Critical-Impact** [comment]
Sorry for not following up on this one, if you update to the latest live version does this still happen?

**Comment by Critical-Impact** [comment]
Closing this for now as I believe it should be fixed with the new tooltip code being used.
