### ISSUE TITLE
AllaganTools not updating inventories consistently

### ISSUE THREAD

**Issue by Ozymandias-Leviathan** [Critical-Impact/InventoryTools#172]
I'm having difficulty as of yesterday with the plugin not giving me accurate values for items (specifically in the FC chest but haven't tested more thoroughly.

Just as an example: There are no Tsai tou Vounou in the FC chest (they were removed yesterday) and the tool continues to show them there.  We also added a ton of Rime Dolomite but the tool continues to show it with only 23.  It seems like it's stuck and not updating from a previous count.

![image](https://user-images.githubusercontent.com/118829381/203340462-29a56dd7-1a32-447c-9463-81f2bcce88ef.png)

From the XLL log:
09:19:10.346 | INF [LOCALPLUGIN] Unloading InventoryTools.dll
--------------------------------
09:19:10.954 | INF [LOCALPLUGIN] Finished unloading InventoryTools.dll
--------------------------------
09:19:12.068 | INF [LOCALPLUGIN] Loading InventoryTools.dll
--------------------------------
09:19:13.276 | INF [InventoryTools] Migrating to version 10
--------------------------------
09:19:13.306 | WRN [XivCommon] [XIVCommon] Could not find signature for UiAlloc (GameAlloc). This functionality will be disabled.
--------------------------------
09:19:13.330 | WRN [XivCommon] [XIVCommon] Could not find signature for Examine. This functionality will be disabled.
--------------------------------
09:19:13.366 | INF [LOCALPLUGIN] Finished loading InventoryTools.dll

**Comment by Ozymandias-Leviathan** [comment]
Sorry just found the discord thread, I think you're aware of this.

**Comment by Critical-Impact** [comment]
Should be fixed in the newest version, can you let me know if its not.
