### ISSUE TITLE
allagantools not highlighting like-items in my inventory to put away

### ISSUE THREAD

**Issue by gaypirate24** [Critical-Impact/InventoryTools#174]
AllaganTools is only highlighting like-items in my retainer's inventory, and the tab that has the duplicated item. It doesn't tell me which item is duplicated via highlight. 

Filter export was the following and it was working fine before 6.3:

H4sIAAAAAAAACn1Uy07jMBTV/AnyOos8oemuFBDVAGVoEQvEwk1uWmtcO9hOqw7i3+c6bkJCIxaR7HPuO+f61wdZ0hWHWU7GJMijGNIoD0Pfj4PUp/FFmCVFGo0iOroYAfHIVNHCfHnQIg/PaZquojSOYZWOiqQIi7g4D/wgp9RHjweAXD9BoUBvyNioCjxyy9Ybjp+5lzmQse+RhaxUBjOxA2GkYqDJ+PXNIzMD22c2pQbWUh1sytc48eKRF6de4ntJ4CWhl0Recu4lqXfuH10WQFW26bkhc/1esXLBpflO1P3cgi2IjKOw22UXrSNLdeJ+BdowQQ2T4rQBfftOxqLi3J6nknPIDMPADfhAt3gmj5U5o3t6ONticMUo1zi6q6rkLENAzwU/NB43jKOJLUbPxBMYygQoTPcTey2qLRkHGJLpktPDTGB3uvkd8xLERL8wkcs9GReYHME/FRWGGUxLsJTZHeyAu/OiZIqZlRRWAcS14NK6uzsvDyU2hmP7DTZGHK2KPC7CVRLSOIz80apI4iQYjTJUXRgGpNHAhPOTplq9vGxAYLAJx1HZCT1rmD+5fEysv8xzmMptycFA/iT3um2qTTHdUEUz08nR+YtDJTQCzXiFwZXUug0xEOFHuxsF8A8L5NVW6G+gFd43phP2qDynrvitqaoHB31FDva62MhyAZzjzB4Vy6wAiUMvq0MfvKfqL5jJDhRdwwm+lIbyU3JKxSVcyqpenUb8kx1l3O7UxCzZFvKHevcdO9/jrO0+4VMwy6Q4+fE4Ezk06GGD5u/dMd0nUPXDHnZxlWm5jpgcM5TyxKgbvSfHI9YJ8hN3vS3t2jmDWhG2jysoaMXNl5SZFXhNYy73kB5dGv281rN01+Oethe7nu2l2fUWOOqqud5JfIWs/hqgq0mHoeqGxHspJQcq3Ioi+vFZ1ydVD1kYu749aCZQ09A3e2bCnADTjUTd9WEuxXoAd2kGiHbIeHWX+gG1Tziyc5Xb5U0+/wPZIjVELQcAAA==

**Comment by Critical-Impact** [comment]
I believe I've replicated this. Next build will have this fixed.
