### ISSUE TITLE
Free company chest data getting lost when logging in another character

### ISSUE THREAD

**Issue by drejjmit** [Critical-Impact/InventoryTools#175]
**Describe the bug**
Free company chest data is getting lost when logging in another character. Even tho i never opened Free Company chest on that character.

**To Reproduce**
Open Free company chest on Character 1
Login Character 2
Back to Character 1 and the Free company chest data is gone.

**Expected behavior**
Previously it just cleared Free company chest if you opened the chest on an Alt, like it should be. 
But i could still see Free company chest data from my main.

**Dalamud Information:**
Allagan Tools v1.2.0.13

**Comment by Critical-Impact** [comment]
Have replicated, the inventory scanner was not freeing it's cache on login/logout.
Will see if I can sneak it into the next build

**Comment by Critical-Impact** [comment]
This should be fixed, can you close if you can no longer replicate.
