### ISSUE TITLE
Inventory filter does not highlight matched item in the first slot of any bag

### ISSUE THREAD

**Issue by diwo** [Critical-Impact/InventoryTools#176]
**Describe the bug**
Inventory filter does not highlight matched item if the item is in the first slot of any bag.

**To Reproduce**
1. Open inventory (reproducible with any inventory interface settings)
2. Place a level 80 equipment on the first slot of bag 1 (reproducible in other bags)
3. Filter using `level:>=20` (reproducible with other filter expressions)
4. The equipment is not highlighted, expected it to be highlighted
5. Drag the equipment to a different slot in the same bag, the equipment becomes highlighted
6. Drag equipment back into the first slot, it is no longer highlighted

**Dalamud Information:**
Do you have testing enabled? No

**Filter Issues**
If you have an issue with a filter not working can you please export your filter configuration from settings and paste the export in the issue.
```
H4sIAAAAAAAACn1Uy27jIBTV/ArrLJynU+/yaBVr2mYmD3VRzYLAdYKGgAs4Vabqvw+Y4NqJ1UiRfM+Fc1/n8uMDbfCOQ0pRgmAwHIyjeDQakbsBiUfjXjaiWZ/GOCbRqD9EHTRTODNfN7LhDmg369JhFg0ACB6MdngcxwPoEwzljWcAqleQKdAHlBhVQAct2P7A7d88SQooiTpoLQtFIBUnEEYqBholr386KDVw3LIZNrCX6uxCBnQNWJHDtef+rWD5mktz7ShTXoCLiZJ+r15IHS2Zpbq5PgdtmMCGSXGbo168oUQUnLvvmeQciGGWOIDP+Gi/0YRz2455kXNGLL1eCn4ORx4YN6BcdJ2KFRjMBCjL/533XhRHlHQtJdM5x+dU2HJ0aPEyBzHRL0xQ+Y6SDHNtwd8FFoYZGxbZVNJHOAH33+ucKWZ2UripIp+zD+tt/70551CG/AmOo9vFNIpIFHd72eDuzk68F/XGXfuLaRZFMQpztaXXirrSwMsBRKh0q2G58rGY2Ad0wSjM5DHnYICu5LuuCqroZwesMDE1/trImuE9ZxAc4YUlV1LriiIcaQz9m3MPCuCfTZAXR6GvQKeyK0+N9iKzUkr1tG7xZjX1ai/3DjJfA+e2a78UI05vyKPT4twEn7D6C2ZyAoX3cINvpMH81jnDYgpTWZSbErQ+OWHG3QpNzIYdgT6X2+y9y3fbbbc+drlTIqsJV2O3XZFtrW4/EOb3yHTTYTXffsPtqTKVryYn72kLeXOozt4Q5AWrkXznuz/mbun8gVITro45ZLjg5kvMzEm8dNtY/mm8XAkKei176c3LllaGW87KCJteARdhBfNREq/AAPjpTyVW9ImJcvJtvrV9MsQcW95CXISN7BvYpvOplByw8Nts0Y/PshCpGsjauE1vQKmw6ofmsS0T5gaYHaRNswlzKfYtuA/T4qimYU1vlO+se9qtd6mo2/Po8z+Qg/iUKAcAAA==
```

**Additional context**
v1.2.0.14

**Comment by Critical-Impact** [comment]
I haven't been able to replicate this but it's possible that it broke due to the retainer parsing causing a crash. I've got a new build waiting to go up(in the dalamud queue). I guess give the new version a go when it comes out and if it's still not working I can look into it further.

**Comment by Critical-Impact** [comment]
Let me know how this goes on the latest version, will close in 3 days time if I get no response.

**Comment by diwo** [comment]
This is still happening for me as of version 1.2.0.18

**Comment by diwo** [comment]
After investigating a little more, it turns out I'm mistaken. This is actually a bug of another plugin. Sorry for the noise!
