### ISSUE TITLE
Allow limiting shown owned items on the tooltips to characters on the same server only

### ISSUE THREAD

**Issue by Joshtst** [Critical-Impact/InventoryTools#181]
Made a request in the discord and was told to make a post here. Thank you for the great plugin!

**Is your feature request related to a problem? Please describe.**

I have alts in another server to play with my friends and the items on my main show up on the tooltips too. It would be great to have an option to show the owned items on the tooltips for characters in the same server only.

**Describe the solution you'd like**

It would be great to have an option to show the owned items on the tooltips for characters in the same server only.

**Comment by vm0d** [comment]
I'm also keen to have this option.

**Comment by Critical-Impact** [comment]
This has been implemented, small bug in the current implementation but a new release is in the plugin review queue. Any thoughts/suggestions please open a new ticket
