### ISSUE TITLE
 I'm not sure if this is a bug ,but

### ISSUE THREAD

**Issue by kitanami** [Critical-Impact/InventoryTools#183]
Thanks a lot for your plugin,Critical-Impact,I like to use it to help me count the material of the submarine.
I like "Item in retainer/bags"list,except this time:
![%3~{S{HI8`%C(@FG%RIM} V](https://user-images.githubusercontent.com/68011232/219210465-bd8e88b4-3641-478a-9113-3c6357766765.png)

When I reduce the size of the window, the "Item in retainer/bags" list takes up my entire window
The crafts list is working but it's a little wide and text is disappears when getting close to the edge of the screen.
like that:
![ZVX)Y3L9G567A$9AG{RDB8F](https://user-images.githubusercontent.com/68011232/219205517-1a835a54-a2ba-4a18-bb3f-24415e08a7ea.png)

![~T DD10NOOJBSE5EUPJRE4D](https://user-images.githubusercontent.com/68011232/219206398-6a9b300e-1284-4d66-8bc7-e7aa3c08cccc.png)

I'm not sure this is a feature or a bug, but because of this I prefer to use smaller craft lists, aside from the embarrassment above.
By the way, if I turn off all the "Item in retainer/bags" list options in  settings,it will become like this:
![%X(`W{7X}A}281KM)$VMAAO](https://user-images.githubusercontent.com/68011232/219207241-b080940c-b430-4432-b21d-f820c4b1ee02.png)

![J`(MN4`7Q63D(`$WJA) EB](https://user-images.githubusercontent.com/68011232/219207446-f2786d9f-495d-411a-8b8c-67781f742e12.png)

If you can, I hope that the height ratio of the "to craft" list and the "Item in retainer/bags" list can be adjusted freely, rather than fixed.just like the table height of excel?
Thanks again put up with my bad english because I used Google Translate for most of the sentences. ; _ ;

**Comment by Critical-Impact** [comment]
What version are you currently using?

**Comment by kitanami** [comment]
looks like 1.2.0.5
![KQG`$YTI@C(251M$D@H{14](https://user-images.githubusercontent.com/68011232/219928730-50bea639-8bec-42e6-aded-b2129aa9cae6.png)

**Comment by Critical-Impact** [comment]
There is not much I can do to help you, that version is very out of date, if someone has forked my plugin you will need to work out where they have forked it and ask them to get it updated.
The latest version is 1.2.0.18

**Comment by kitanami** [comment]
I see ,thank you so much!
