### ISSUE TITLE
Can't use comparison operator in several filter fields

### ISSUE THREAD

**Issue by Dekirumonka** [Critical-Impact/InventoryTools#184]
**Describe the bug**
FYI, I'm at CN server. 
The comparison operator( <, =, > etc.) is working fine in some fields like marketboard price, but when I input it in Basic-Quantity field, the filter will give no result. 

And the Market-Market 7 Sale C (I can't read the rest of the field name, because there is no space left for it) is also not working, but unlike the Quantity fields, it simply can't input any comparison operator. 
And when I copy & paste the string ">1" to this field, it will crash the game and give the error below.

**To Reproduce**
1. Create a new sort filter
2. go to the filter and find the Quantity field in Basic tag, and Market 7 Sale C in Market tag.
3. Copy ">1" and paste to the fields.

**Screenshots**
This is the error that pop out when I paste >1 to the Market 7 C field
![Snipaste_2023-02-18_16-45-16](https://user-images.githubusercontent.com/17879091/219851069-79f057d4-8b1f-42ef-82d8-5c290b5095a1.jpg)
.

**Filter Issues**
The Quantity Filter:
H4sIAAAAAAAACn1UTU/jMBDV/hPkcw9NGijpYaW2gIi20KVpxQHtwU2mjbWOHWynqIv474zjJqSbiEMk+z1nPt/Mj3eyplsOUUomJPBH/vYKUi8ILoNhOrz2gjQMh1e7bTi6TFNKBuQRINUr2CnQGZkYVcKA3LN9xvEzDzIFMhkOSCxLlUAkDiCMVAw0mbz8GZDIQL5hc2pgL9XRuqzRGKhKsv+Z29eSFTGXpvcXqTr4DWjDBDVMiq5zff9KJqLk3J7nknNIDMPUa/CR5njGDN8urO2LO8YNKMz5piw4S9CVXgp+rJ872kaiI7ECQ5kAhb6+Y29FmVcFumG64PQYCSw+/rOjXGMhlwWIqX5mIpVvDfhUUmGYQb8EY4kWcADuznHBFDNbKWzviEvgFHR1d+f1scC0/AH5BdbGcLzzPUg8z6d+kFyF4XgUDOl16Cd+SMcQkLp7U847WTWdfs5A1OBGw3LlfDGxr9HGyDyjiiamZaXVpT4ntXgSXqYwV1LrxkSPhW/f3SmAf4C9LnPR5/6kn0ojbedd/Dzmbk5xJosYOMcK/FYssUIiDp2Vx3Pwgaq/YKYHUHQPHXwtDeVdck7FDGayxNp/iXh6oIzb6Z2aNcshfazmz7HLN6ypnQtUW5RI0WkhVkX2FbT/Qd2lBdPnBAq4/w87gMo0XEsajulz2XnUtt4iG6xl5DvuNi/sAJ1axfKCo2Dozpp0O8sxjVBeqpK562mwmoudp+ZSD2cDnPRTXxcS94YVWg20xecwXE0zKTlQ4WYI3b9/VLFIdYbExs7XF0SeqqXw0yNIRgIVC+c/bJgwHWCeSRTVOcyl2PfgzmEPUdXOKsFGUV2qRWf3LLJLldoJ9K4/PgGlcPQgXQYAAA==

I can't offer the Market 7 Sale C field filter because I can't input the operator in it.

**Comment by Critical-Impact** [comment]
What version of the plugin are you using and where are you getting it from?

**Comment by Dekirumonka** [comment]
> 

Hello, it was v1.2.0.11, and I got it from this repo: https://aonyx.ffxiv.wang/Plugin/PluginMaster?apiLevel=7

**Comment by Critical-Impact** [comment]
Sorry, there is not much I can do, that version is very out of date
You would need to contact whoever runs the repo and see if they can fork the plugin and fix it for whatever dalamud they are using
