### ISSUE TITLE
The Export to CSV is not printing results for any Game Item Filters.

### ISSUE THREAD

**Issue by Dekirumonka** [Critical-Impact/InventoryTools#185]
**Describe the bug**
First, I'm at CN server.
When I try to export a filter result to CSV, it will only print the column names but no results.
The sort filter will export correct result, though there are some minor encode issue for CN server, that could be solve easily by open the CSV file with TXT editor, and save it as ANSI encode.

**To Reproduce**
1. Create any Game Item Filter
2. Go back to Filter window and click the export to CSV button.
3. Open the exported file and see no result.

**Expected behavior**
print a correct result like other filters.
**Screenshots**
This is the result of the sample filter 100 gil or less(without the source field of cource). If you can read Chinese you will find the encode are not correct.
![图片](https://user-images.githubusercontent.com/17879091/219853209-ace67cc0-9a33-41cf-91c4-bbb5ebd24213.png)

And this is the correct result, which I manually changed its' encode.
![图片](https://user-images.githubusercontent.com/17879091/219853341-e5955cc9-6572-4b41-9509-a6235e84d8c6.png)

This is the result of the sample filter All Game items.
![图片](https://user-images.githubusercontent.com/17879091/219853494-9883ae46-afd1-4c1f-ba70-29027ac4d706.png)

**Filter Issues**
I think all the Game Item filter will reproduce this bug, so this is the All game items filter from sample filter.
H4sIAAAAAAAACn1UTVPbMBCd/hNG5xwCMYHkloQvT4G0cSgHpofFXseaypKRZJiU4b93ZWHHrj0cPCO9t9aTdt/ut3e2hWeBYcLm7Gw2ncYIU5icQhAnYwgAk7PT2XSSjo9nxykbsXvExGww1WgyNre6xBG74btM0GfvVIJsPh6xSJU6xlC+orRKczRs/vR7xEKL+QNfgcWd0nsnWaMRgo6z/5nLl5IXkVB28Bele/gFGsslWK5kX9zcvLC5LIVw65USAmPL6ek1eA85rdlCiKNrWh45EUNPvigLwWNSMmsp9nX0FRcWdRUTyg1a4BI1SX3FXsoyr/JzwU0hYB9Kyr2p07guUC7MI5eJemPzFIQh8GcJ0nJLsoyuEt7iKwq/jgquuX1W0lXOVYbu7GX93q+3+4IeFYzYd3RnBMnseRrMgpPz9DhIqb7j80k8S+MAknM4mSSsrh1lofeops6PGcoafDC43ngtLnc12hyyykBDbFuntGo0JFJbJxZlgiutjGmOGDjhy7grjfgXqdJlLofkP91TOaQt3se7d+6/KcpUEaEQlIEfmsfORsyjy3LfBe9A/0G7eEUNO+zhW2VB9MkVyCUuVUm5P1h48QpcuN5d2C3PMbmvus+z6zfKqesKMlsYK9krIWVFDSV0OKCu0i03XYL8O/yHaz9tG65lDc8MSfaC2qe3yAZrHfIVd5kXroE+S8XzQpBhIHVH+onlmcYoT1XK/PazsZrNYXw1UHd2NbBrft+vHaiLbIB6+PBPda1DuKmv6X48BDkzXIPNUGPSRX+QfTMwLXgR0wxtx0Vk0636hTRldOWwhiGrXmmV9ykankulBIL0fU4pev+o8qV0B4msmwEdKJSUFuyGPXBpe8AqU6TYhYWSuwHcywwQVbqcR2nrN36G0/wndq0TNxtOxh//AHm+wM/1BgAA

**Comment by Critical-Impact** [comment]
Closing this as well as it's working on the latest live version, if you use an old version there is not much I can do until the forked version is updated
