### ISSUE TITLE
Large Item Databases have major issues under Wine

### ISSUE THREAD

**Issue by elshandra** [Critical-Impact/InventoryTools#186]
My Inventories.json is ~60mb, and it causes several issues under Wine.

1) Searching for an item by name in /atools, All/Name hangs the game for several (10-15+) seconds. 
2) Sometimes the game won't launch until the plugin is disabled at the XIVLauncher splash screen. You can load the plugin fine once the game is loaded, however.
3) There reaches a point where new characters data just won't be saved. Pehaps there is a hard limit of ten characters, or it's just coincidentally round. This data will be available in memory if you swap between characters, but never seems to make it to disk.

I had these issue on Stable (1.2.idr), and have also been able to replicate on Testing (v1.3.0.6)

Replicating from Discord, Mainly to provide Data Files.
[LargeITDB.zip](https://github.com/Critical-Impact/InventoryTools/files/10775535/LargeITDB.zip)

FWIW, Running via Lutris, on lutris-GE-Proton7-35-x86_64

**Comment by elshandra** [comment]
I was able to make a huge dent in this problem by switching from the (generally unsupported) lutris install, to the native xivlauncher install for debian. The flatpak should work equally as well.

**Comment by litori** [comment]
On Windows and was having issues with lag on item mouse over.  Looked at the item database and it ballooned to 800mb in the pluginconfig folder for inventorytools.  Had to delete the database and start over to remove the lag.

**Comment by Critical-Impact** [comment]
@litori how many characters and retainers do you have? There are some optimisations in the pipe for the file size of inventories but it sounds like an issue with the calculations of where your items are taking too long.
Mitigation of that is possible but it might have some downsides
I guess let me know the counts and I'll see what I can come up with

**Comment by litori** [comment]
4 character with 2 retainers each.  After flushing the inventories.json 2 hours ago and only had logged into one character, the file is sitting at 7mb.  The ingame lag so far has gone away.

**Comment by Critical-Impact** [comment]
That's really odd, if you can could you send me your inventories.json file?
Would be interested to see what it contains as it shouldn't balloon that much

**Comment by litori** [comment]
[inventories.zip](https://github.com/Critical-Impact/InventoryTools/files/10791731/inventories.zip)

Here is the file.  Compressed down, it is only 4mb.

**Comment by Critical-Impact** [comment]
Thank you :)
I will see what I can work out

**Comment by litori** [comment]
Just to note, I was on the testing release and I thought that was the issue so i reverted back to the stable.  Going back to stable didnt help any so reading the issues here on github that i figured out it was the inventories file.  Since the flush, i'm back on the stable release.

**Comment by Critical-Impact** [comment]
The file has revealed a bug, free company bags aren't cleared each time the scanner detects a change in the FC chest(the scanner cache is wiped each session) so the more you play the larger the file would get.
Will get it fixed and push it out with the new testing version

**Comment by litori** [comment]
just to give an update.  On the current stable release and now the file is up to 100mb.

**Comment by Critical-Impact** [comment]
Hi, inventories are now saved/loaded into a CSV. The overall file size has decreased substantially and along with it the load/save time.
Let me know how you fare with the latest verison. Closing this issue, feel free to reopen it if you continue to run into issues.
