### ISSUE TITLE
Filters not saving

### ISSUE THREAD

**Issue by PrincessRTFM** [Critical-Impact/InventoryTools#19]
Filters apparently aren't saved automatically, because I lost my filters when I relaunched the game. Unfortunately, I can't find any kind of manual save control either, so it seems like filters _can't_ be saved at present.

**Comment by Critical-Impact** [comment]
It should save on game close but it's possible thats not happening
I'll setup an auto save and also consider having a save file for the inventories and the configs
That way even if something goes wrong the configs should still exist
