### ISSUE TITLE
Missing NPCs from More Information

### ISSUE THREAD

**Issue by Taurenkey** [Critical-Impact/InventoryTools#190]
**Describe the bug**
When looking up more information on items, if the item has shops/vendors that share inventories then only one will be listed. For example, items from the GC vendors will only list the Flames Quartermaster, even though you can buy the same item from the other 2 GC quartermasters. This also applies to NPCs like the Calamity Salvagers, it will only list the one in Ul'dah. This also seems to make some items just omit having vendors, such as Iron Ore, which can be purchased from 6 different vendors but the plugin doesn't report any of them.

**To Reproduce**
- Look at the more information window for certain items such as those listed above and check the shops heading.

**Expected behavior**
All vendors to be listed for all items.

**Screenshots**
![image](https://user-images.githubusercontent.com/30053704/221550259-3bc5f20f-e1d2-4784-a129-f36995e9ab26.png)

**Comment by Critical-Impact** [comment]
So there's a few things happening here,
1) I did have a artificial limit in the logic that'd only show items from GC vendors based on your characters GC. I've removed this in the testing version that is coming out.
2) Calamity salvagers are a different matter and I'll look into it
3) The vendors for iron ore, which ones don't show up?

**Comment by Taurenkey** [comment]
For the iron ore one, none of them. There's a vendor in Limsa that sells it ([Soemrwyb](https://eu.finalfantasyxiv.com/lodestone/playguide/db/shop/a783601ac62/?item=ad4b9905828&type=gil)) along with vendors in the housing districts. There's 2 vendors listed in the GilShop sheet for it, one of which will be the NPC in Limsa and the other one is the same vendor but for the housing districts. 

I realise I picked a low level item, but from my experiences with going on a craft binge sometimes it's the lower level stuff that you need to remember if it's on a vendor or not for convenience.

**Comment by github-1348A55** [comment]
I myself have recently noticed that some stores are not showing up.
Store information of "Gridania" and "Limsa Lominsa"  is not displayed. (probably all the stores)
But "Ul'dah" store information will be displayed.
It is still unclear if there are cases where other countries or vendors are not listed.

As for "Item Infomation Window" I have a separate report.
I will make a new post later.

**Comment by Critical-Impact** [comment]
Please try the latest version, I've added in some vendors manually as their data does not appear in the game. I've unlocked vendors that might not have actual locations and calamity salvager shops should show up now.

I can find vendors in Lumsa Lominsa, if you can't find a specific vendor can you let me know which one?
