### ISSUE TITLE
Allagan Tools has not displayed icon previews since 6.3 for me

### ISSUE THREAD

**Issue by goldirocks** [Critical-Impact/InventoryTools#191]
**Describe the bug**
AT hasn't shown preview icons for items for me since the 6.3 update.

**To Reproduce**
I don't know, but for me:
Open AT item list
![image](https://user-images.githubusercontent.com/32187006/224166528-31d87d3f-be44-4f8e-b529-b670704a0518.png)

The icons in the More Information window display fine, though.

**Expected behavior**
Actual icons for each item, or not having an empty column where they used to be.

**Screenshots**
As above.

**Dalamud Information:**
No testing enabled here.

**Filter Issues**
I assume not, since this is on any tab, not just my filters.

**Additional context**
It's happening on multiple machines for me, so either my AT config is toxic or something strange is reproducibly going on...

**Comment by Critical-Impact** [comment]
Hi, so there should be a setting within the filter configuration in the display tab called "Table Row Height". See what that is set to, if it's 0, set it to 32 and see if the icons appear. 
The plugin has a series of migrations that it runs, and one of those was supposed to put in a default value for table row height so if it is the case it's 0, i'm a little unsure as to why that is the case.

Let me know how you go

**Comment by goldirocks** [comment]
I don't seem to have something like that.

Under Visuals, I see Tooltip Location Limit, which I already had to adjust to 10 after it defaulted to 0 one day, that was fun.

Adjusting this to 32 from 10 does not help this issue, but it does help #192, so that's nice.

**Comment by goldirocks** [comment]
That is indeed set to 0 for all my filters, thank you.

That's...a very confusing setting, and I would never have thought one that existed.

**Comment by Critical-Impact** [comment]
It's for allowing people to have more compact filters. I'll see if I can work out why the migrations didn't fire. Regardless glad it's working now, I will close the issue.
