### ISSUE TITLE
Crafts window mats quatities - refresh button/auto refresh after gathering/crafting

### ISSUE THREAD

**Issue by LiveLongGiraffe** [Critical-Impact/InventoryTools#193]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Hi, I'm a big fan of the tool, but kinda still a noob with it, so sorry if this functionality already exists, or there's an option in the settings somewhere for it... or maybe it just isn't working on my end... the only way I've seen to have the numbers for mats in the "Available" and "Missing" columns in the AT-Crafts window (To Craft section) updated is by disabling and re-enabling the plugin. I appreciate any response, and thanks for all your work on this plugin!

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by Critical-Impact** [comment]
Hi, what version are you currently using? Can you also try switching to the testing version that's available and see how you go?
Filters and Craft lists should update automatically as your inventory does, if this is not the case then it's possible the inventory scanner is crashing in which case I'd need some logs to help further.

**Comment by Critical-Impact** [comment]
Latest and greatest live version should have this sorted, closing the issue. If you continue to have issues please reopen.
