### ISSUE TITLE
Deduplicate shared FC contents

### ISSUE THREAD

**Issue by retep998** [Critical-Impact/InventoryTools#195]
**Is your feature request related to a problem? Please describe.**
I have multiple characters in the same FC. If I have "Limit to items belonging to the current character" disabled I can see items stored on my other characters, but this *also* means I see items stored in the FC chest for each of those characters. This causes the total number of the item to be overinflated as a single stack of 100 doodads in the FC chest gets counted *multiple* times.

**Describe the solution you'd like**
Detect when two characters are in the same FC and deduplicate FC chest contents when so.

**Describe alternatives you've considered**
The only alternative is either ignoring the duplicated entries and incorrect total, or limiting the view to only the current character and not being able to see what my other characters have stored.

**Additional context**
![image](https://user-images.githubusercontent.com/666308/228084894-66d74b5f-ce02-42b3-ac19-5330c4ae022b.png)

**Comment by Critical-Impact** [comment]
Give the testing version a go or wait for the live version to be updated(it's currently in the dalamud plugin queue). FC chests in that version are tracked as their own unique inventory with an ID so if you have multiple characters with access to it, it'll still only ever display one set of items.

**Comment by Critical-Impact** [comment]
This is now on live, closing it, reopen an issue if you run into problems with the FC tracking :)
