### ISSUE TITLE
Incorrect quantities displayed in the Crafts window.

### ISSUE THREAD

**Issue by 13522923001** [Critical-Impact/InventoryTools#204]
I'm using the Crafts window to track mats and pre-crafts. Right now, I'm getting all sorts of inaccurate quantities for the Available and Retrieve columns 

To preface, I have two characters, both with 2 retainers, and an FC Chest.

Here are my Crafts settings
![image](https://github.com/Critical-Impact/InventoryTools/assets/134285707/a691804c-c547-4921-9289-304ab4387719)

An example of the Available issue
![image](https://github.com/Critical-Impact/InventoryTools/assets/134285707/3f0bccfa-4f02-4ada-b9e2-c615ba4ebe24)
![image](https://github.com/Critical-Impact/InventoryTools/assets/134285707/0a37b440-6137-4a0c-8678-949db2b79b9c)
If there was 1 available but wasn't in the current character's inventory, then there should be a 1 in the Retrieve column.

An example of the Retrieve issue
![image](https://github.com/Critical-Impact/InventoryTools/assets/134285707/949cf34f-01a6-4cbf-b07a-70d9b01db16f)
![image](https://github.com/Critical-Impact/InventoryTools/assets/134285707/6d6d895c-af61-4043-acf4-ab638cf98d29)
If there were 17 to be retrieved, then Available should be at 34.

I most likely did something wrong with the settings that caused this issue, but I don't know what settings I should turn on or off. I'm overall just very confused by the "Source" and "Destination" settings.  Any help would be grateful. Thank you!

**Dalamud Information:**
Do you have testing enabled? No. I don't know how.

**Filter Issues**

Here's my Craft list filter
H4sIAAAAAAAACrVVTXOjOBCt/Ss6+4AdbBPf/JEZU5vEM3ZSOaTmIKPGqFZIjCSS8qby36cFBoNhXXuYOVCF3lN/qPW69dcHeaJ7ASEjMzK5GQeRF49v6RD8cXBLGcCQxfvAG/v7wJ+SAVlqGtuzBRtPp3uI9zfUH/sQTwOPQQATCKZsxCKfocUjADNbiDWYhMyszmFA1vyQCPzsg2JAZt6A7FSuIwjlG0irNAdDZq8/BiS0kD7zJbVwUProQlboDqiOkkvm7mfOs51Q9pIoUl6Di0lmI695kAq9GZ08K90xX4GxXFLLlezmaNY/yUzmQrj/pRICIsvRcQU+0hT/ye4omKZYkVWeCR5hBLOR4ljt+sKFBe0SMKHcgqVcgsYQ19g7madF+VbcZIIeQ4knQpuYCoNl3mQg5+aFS6bea/B7TqXlFuMSzCW8hzcQ5f8u45rbvZLuZkmZdxm3XJf/T8cMTxMMyN/gfDDP89hkz25pPPGpH+y98TDyfTryhxEb3gakutu5EJ1T1cxa5Qa68BcNsFRpRiU/s7V4XhKQmMFcvNOjwTjPBjbbMkkuD+ftrPAhwALbqvdzeeowy4RqGqGZqQTauO++vNt0b5btLX3nC2UkcsxNK2PqDHrMr+5zsf/F6CJPpbkAncIvmIbbk8T5ZVpN/HXY1n5vrXaJynYgBNb8m+aRkzop0UV+bIMPVP8Ddv4Gmh6ggz8pS0WXXFK5gIXKiyat2mz+Rrlw3Tu3TzwF9lgMkpLdvONduc7FxggjJTvCwaKovkr3b6hu/56bNoG91m/hRoS2NdcQY8n0hexsanpvyfmENZxc4+7SzPX6yfNBKg3r765z3Jhr+C3U4o64gpjmwp67hLveKWjcXg7spl5elBas1lCtt9ei9OXyNEvqReFsnqpc2voea7KaTzVwkmW1vFdRqd8SQIG2hf4/A28BnwoNrBO3m1HLirJjH/Es6TW7q05R4I0j1O2wUFSzBy6LVvgPrmiZ9oZ5hAcz3JXoNGewHKYd9yu1CehzBRdKCaCynJ1Yw4/P4iaVbiE76+ZqCwolDgtob1tBxFMqWtgzl7YDLBOFibdhoeShBy9D9xC1bHFZLoo3EmXwUTzmbgyM/Bvfx6ko6MEUQ2GLGWZQTQizyW2WF3bVSPuWUFPLvBJGpRgyG34O2t7Hf9T75I96n/5e7z/wUjaauRfK//wF7/63rl4KAAA=

All Game Items filter
H4sIAAAAAAAACn1VTW/iMBDV/pPKZw58BCjc+GhLtG3pAt0eqj0YZ0KsdezUdlqxVf/7jhMSEhL1EMl+bzwzHr+Z/PgkO7oX4AdkSjwYjfujPngwod4IwkmP9Xr7fhiyAfQmoUc6ZKFpaM8neiwYDMNwNNmPwGMwosybMG8wZuANhtcQ4IlHgMBsINRgIjK1OoUOWfFDJPCzDyoAMu12yFalmoEv30FapTkYMn390yG+hfiZL6iFg9JHF7JAt0A1iy6Zm7eUJ1uh7CWRpbwCF5NMB/3qRapo5lnpxvElGMsltVzJZo5m9UamMhXCrRdKCGCWo+MCfKQxrslMiKs7XF65IAYrs0wTwRlGMmspjoX1LRcWdGbjyw1YyiVoDPUdeyPTOCvjkptE0KMv8WamqPY6ATkzL1wG6oNMQyoMgr9SKi23GJZgKv49vIPI19uEa273SroHdg+IOedh832+3h0TvJTXIT/B+WDheDjsDkeB1x953vVwMgnH0A27w/4e5ROEpHhirELjUiWzUqmBJnyrARYqTqjkZ7bU0EsEsgCfDaw3eYJcHs6mQXZegIVgoz5MWYUyxCKimjI8VvqvPHlbznW6NcO6SdvdfMlEirlpZUyZQcvxb+1c7H8YXaSxNBegE/kFU3F7Ujm/TKuJ16/SLNY2UskWhMCiP2nOnNxJjs7TYx18oPov2Nk7aHqABr5TloomuaByDnOVZo1atNrsnXLhOnhmdzyG4DEbJjm7/sDHct2LTeEzJRuqwaqotlK3GxTPf89NncA+az/hxoS2JVdRY860hWwYVb3X9HzCKk6+427ixDX6yfNBKg2rX65t3Kir+M3k4q64hJCmwp7bhLvmyWg0z4d2VTAvSougFEMpuNes9Pn2NEjKzXmql1B9pJewG3b5fKpBdWRDcWadz1SE78xNkbo7eDZyorqjNgINQR19wltF1FTgGcNfS9XOyX2nfgNOVZ0ptWRQ8rdaxU0KfxZtHTlXSgCV+dhC9PMrq6HSNWRr3UirQb7EUkHdbAmMx1TUsGcubQNYRAozq8NCyUMLnoduIUrB4Dbf5P82/C8iu9aBm1Le13/crgfVZQgAAA==

**Additional context**

**Comment by Critical-Impact** [comment]
Should be good in the latest version, please open a new issue if it's not :)
