### ISSUE TITLE
Suggestion: Remove added categories from dropdown list

### ISSUE THREAD

**Issue by nageki** [Critical-Impact/InventoryTools#21]
For instance, I've added Arcanist Arms as a filter category and it would be useful to have it removed from dropdown to quickly see what other filter options are left. 

![image](https://user-images.githubusercontent.com/75861784/138154222-53649452-6062-4c1f-bec5-67d44d7e261f.png)

**Comment by Critical-Impact** [comment]
Great idea, I've implemented this and next time a build goes out it'll be in there :)
