### ISSUE TITLE
Wiki links in the More Information windows

### ISSUE THREAD

**Issue by SayuShira** [Critical-Impact/InventoryTools#210]
**Is your feature request related to a problem? Please describe.**  
At times I want to quickly gather information about an item, or currencies and the content it is available in.
The More Information window, while providing Garland and Teamcraft links, doesn't enable this currently.
More Information and those websites provide factual information about the item, its use, recipe, shops etc. but no explanations or overview of the content or a link to such a resource.

E.g. Hi-Cordial: I see that I can buy it with Islanders Crownies. Oh but where do I get these? What is Island Sanctuary?  
Those questions are unanswered currently. My suggestion is to add a link to a wiki, that can add this extra context.

**Describe the solution you'd like**
I would like to have an Open in Wiki Button just like Open in Garland or Teamcraft.
My wiki suggestion would be the Consolegame wiki, as I find it more useable and easier to read compared to gamerescape.  
But there is room a more than one button anyway.

**Describe alternatives you've considered**
My current alternative is using Wotsit to type "?Islanders ..." and select the wiki there.
This however is a bit cumbersome if I'm currently using my mouse to look over my items, not my keyboard to type.

**Additional context**
Wotsit has a working [function](https://github.com/goaaats/Dalamud.FindAnything/blob/master/Dalamud.FindAnything/FindAnythingPlugin.cs#L216) to open corresponding wiki pages that might be useful as a reference.

An artful prop:
![image](https://github.com/Critical-Impact/InventoryTools/assets/104025906/9fec9a11-0863-40bc-a4b8-e6aff47fbbfe)

I'm open to try implementing this myself.
But would like to ask for your opinion and feedback on this.

**Comment by Critical-Impact** [comment]
Available in the latest version
