### ISSUE TITLE
Potential new "Quick Crafting List" feature

### ISSUE THREAD

**Issue by wirchtalksgames** [Critical-Impact/InventoryTools#214]
**Is your feature request related to a problem? Please describe.**
Managing crafting lists is great for larger or multi-item projects, but sometimes you just want to craft one item quickly and move on, but to use the crafting list feature in AT, you always need to add items into crafting lists. In the case of these quick crafts, the "add to new crafting list" function is great, but you'd still have to delete the crafting list manually once you're done with it, which can take a couple extra steps that you could save with a potential new feature.

**Describe the solution you'd like**
Add a new "Add to Quick Crafting List" feature. These "Quick Crafting Lists" would function similarly to regular lists, but they automatically get deleted when all the output items are crafted. This would be great for when, for example, you already have a full set for a black mage, but you want to craft just a weapon for another caster class. Regularly, you'd just add the weapon to a new crafting list, craft the item, and then delete the list to maintain order in your crafting lists panel. With a "Quick Crafting List", you'd craft the item and it would automatically get removed once you're done. The way this could work is that you could make it so that you can only have ONE Quick Crafting List at any given moment, which would distinguish this feature from regular crafting lists. You can add multiple items to this QCLs, just like their regular counterparts; the only exclusive feature is the auto-delete function, as well as the fact that you can have only one active at any moment, to keep things simple and concise.

**Describe alternatives you've considered**
Instead of ONE Quick Crafting List, the player could be able to have multiple Quick Crafting Lists (basically regular lists, but with the auto-delete functionality), in case they want to work on multiple quick projects at one moment. However, this might lead to confusion by users who might accidentally start adding items to a QCL when they meant to use a regular CL. In this case, you might add a visual element in the lists panel to tell QCLs from regular CLs at a glance.

**Comment by Critical-Impact** [comment]
Ephemeral lists were added a couple of releases ago and should fufill what was requested
Open a new ticket if you have any suggestions/ideas on how to make the system better :)
