### ISSUE TITLE
Trial Synthesis causing active list to update as if item was actually crafted

### ISSUE THREAD

**Issue by quixten** [Critical-Impact/InventoryTools#215]
**Describe the bug**
When a trial synthesis is completed while an active list contains the item being trialed, the list removes the item from the list as if you had successfully crafted it.

**To Reproduce**
1. Add an item to a crafting list
2. Set that crafting list to active
3. Complete a trial synthesis for that item
4. The item is removed from the list even though you haven't crafted it

**Expected behavior**
The item is not removed from the list.

**Comment by Critical-Impact** [comment]
Should be sorted in the latest release
