### ISSUE TITLE
Allow setting "invert highlighting" option per filter/craft list

### ISSUE THREAD

**Issue by Cirridyn** [Critical-Impact/InventoryTools#218]
**Is your feature request related to a problem? Please describe.**
The main reason I tried the plugin was to have a quick indication in retainer windows when an item is something I want to remember not to sell (e.g. Jhinga, due to DoH/DoL food.)

**Describe the solution you'd like**
I believe since the "invert highlighting" functionality already exists in the plugin, extending it to be an option that can be overridden by each filter or craft list individually would enable my desired functionality (the plugin works as normally intended, but that one list is inverted.) I believe this feature might also be of benefit in other use cases.

**Describe alternatives you've considered**
By toggling off the "invert highlighting" option in the plugin, I've effected the desired capability - albeit at the expense of inverting all filtering the plugin does.

**Additional context**
I could see this thought further expanded to different forms of highlighting per list (tooltip text, emblems over icons, custom highlighting masks.) Seems like a good separation point to not consider that here.

**Comment by Critical-Impact** [comment]
Should be possible in the latest build, it was always possible to set invert highlighting for both the inventory and the tabs in normal filters but it was not possible in craft lists.
I have larger plans to rework the entire highlighting system so I'll close this for now but the plan is to change to something like "Highlight Colour", "Not Highlighted Colour", which could then be customised further for tabs, items, lists, etc
