### ISSUE TITLE
Add "Only" as option to "filter items when in retainers"

### ISSUE THREAD

**Issue by chalkos** [Critical-Impact/InventoryTools#22]
Yes/No is already there. I'm suggesting an "Only" option.
This would only highlight items in that filter if I'm at the retainer, and not highlight otherwise (except maybe the case below).

This could also highlight items matching the filter that are in all retainers when i have the retainer list open.

**Comment by Critical-Impact** [comment]
This will be in the version after 6.2 comes out but I've added a only option to "Filter items when in retainers".

When it's set to Only, it'll enable highlighting if you are at a retainer bell(viewing the list) or if you are viewing a retainer. Any other time even if the filter is active, it won't highlight anything.
