### ISSUE TITLE
Request: add a button to echo a chat item link to item info windows

### ISSUE THREAD

**Issue by PrincessRTFM** [Critical-Impact/InventoryTools#221]
A button in item info windows to echo an item link into the local chatlog would be decidedly useful in several cases.

- Consumables and gear don't show stat effects in the item window. While it may be possible to add the percentage and maximum for consumables, Simple Tweaks adds the calculated actual effect to the tooltip, which would not be included.
- In addition to ST adding stat effect calculations, other plugins modify vanilla item tooltips in various ways, such as adding marketboard information, or context-sensitive hotkeys while an item is hovered over.
- The count/location of owned copies of an item are only shown in the tooltip, not the item window. While again it could be added, this feature already exists elsewhere, and it's not possible to use the vanilla "search for item" feature from info windows.
- It's not possible to try on gear from item info windows. This could be added, but it would be more effort for less gain than simply linking _any_ opened item into the local chat and letting the vanilla context menu handle it.
- It's not possible to create an item link to send to others in the game, which means it's not possible to show someone else the item you're looking at.

At present, in order to get an item link, the only option is to open `/xlitem` and search it up by name, which is usable but decidedly less than optimal.

**Comment by Critical-Impact** [comment]
With this one, you can right click on the image of the item inside the item window to bring up the menu where you can then hit "Link"
If that works, what I'll do is make it so both left and right click open it and when you hover the image it changes the cursor to make it look clickable
My only other thought would be to have a ... button somewhere on the window
