### ISSUE TITLE
Items number played have is not accurate

### ISSUE THREAD

**Issue by a-lazy-cat** [Critical-Impact/InventoryTools#222]
**Describe the bug**

**To Reproduce**
1. Buy A items, put some in retainer's bag(Suppose you put B items in retainer's bag). 
2. disable the mod
3. craft x times, during the time take some items from retainer's bag.(To be special, suppose you take B items from retainer's bag, and you consume X items in total)
4. Enable the mod. The number of the item you have is wrong. 

**Expected behavior**
You should have seen correct number(A-X). 0 in retainer's bag and A-X in player's bag. But actually you see the item you have is A-X+B. A-X in your bag and B in retainer's bag. The mod doesn't realize that you have already used the item in retainer's bag. In other words, each time I enable the mod it doesn't count again. They just used the cache before.

**Screenshots**

**Dalamud Information:**
Do you have testing enabled?

**Filter Issues**
If you have an issue with a filter not working can you please export your filter configuration from settings and paste the export in the issue.

**Additional context**

**Comment by Critical-Impact** [comment]
It's not possible for me to fix this. If you don't go into your retainer after re-enabling the plugin, the plugin has no idea anything has changed. The game does not store a copy of the retainers inventory data(the same applies to the free company chest, glamour chest, armoire and housing storage) so the only way for the plugin to parse the retainer's data is to do so when you open the retainer.
