### ISSUE TITLE
Highlight items based on manual selection / Favorites Highlight

### ISSUE THREAD

**Issue by Froshie** [Critical-Impact/InventoryTools#226]
### Problem
I wish to highlight items I'm collecting for glamour.
Currently, the only way to do so is using Filter's Name Column.
Filter's Name Column has a limit of 500 characters, thus greatly limiting the amount of items within a filter that can be highlighted using this method.
Using currently available method (Name Column search utilizing `||` operator), you can highlight around 5-10 items, depending on the length of their names. The highlight filter method I'm looking to have should be able to support at least 100 items.

### Request
Add a solution that allows customizing a filter in a way it highlights all the desired specific items.

### Suggestions
When searching for an item using Name Column, add a setting in the Right-Click/Context menu that allows persistent Highlight of said item within this filter, until the setting is ticked off. In this case, clearing the Name Column would not remove the highlight. Repeating this process will allow the user to handpick which specific items they want to be highlighted. Additionally, there can be a setting to clear all handpicked highlights, so that user doesn't need to look up all the items and tick off the manual highlight one by one.

### Alternatives
Users can already make a list of items they want to keep an eye on using Item Search Plugin. That plugin does not highlight items in your inventory, it functions more like a "wishlist".
If collaboration with Item Search is possible, the easiest solution method is: add "Export list" function to Item Search plugin. Add "Import Item Search list" function to Allagan Tools plugin. This way, you will directly import any items you want to keep an eye on, and have them all highlighted with much less effort.

### Attachments

CURRENT METHOD
![1  current method](https://github.com/Critical-Impact/InventoryTools/assets/83510075/99882b6d-ab69-4f0b-a0f5-717af524bb63)

SUGGESTION
![2  solution](https://github.com/Critical-Impact/InventoryTools/assets/83510075/b7d75ec1-01c2-4e90-8e1d-6d1dece78bab)

ALTERNATIVE SUGGESTION
![3  alternative solution](https://github.com/Critical-Impact/InventoryTools/assets/83510075/10c19079-5963-4d85-b018-d668ea520d06)

**Comment by Critical-Impact** [comment]
I've added a favourite column and also a favourite filter. With that you can favourite items quickly and also create lists that only show your favourite items. That should get you going and I am working on a curated list filter type that will allow for lists with a specific set of items to be created/saved/loaded so once that comes out give that a go
