### ISSUE TITLE
UI doesn't update after adding/removing items to craft lists via IPC

### ISSUE THREAD

**Issue by AdamHitchen** [Critical-Impact/InventoryTools#230]
**Describe the bug**
After updating a craft list using IPC ("AllaganTools.AddItemToCraftList" or "AllaganTools.RemoveItemFromCraftList") the UI isn't updated, but "AllaganTools.GetCraftItems" returns the correct values. 
The craft list properly updates after some kind of event (Opening a retainer, Toggling "Hide Completed?" in the craft UI)

**To Reproduce**
e.g.
```csharp
    _getCraftLists = pluginInterface.GetIpcSubscriber<Dictionary<string,string>>("AllaganTools.GetCraftLists");
    _removeItemFromCraftList = pluginInterface.GetIpcSubscriber<string, uint, uint, bool>("AllaganTools.RemoveItemFromCraftList");
    _getCraftListItems = pluginInterface.GetIpcSubscriber<string, Dictionary<uint, uint>>("AllaganTools.GetCraftItems");

    ...

    var craftList = _getCraftLists.InvokeFunc().First().Key;
    _getCraftListItems.InvokeFunc(craftList); // {"35645": 1}
    _removeItemFromCraftList.InvokeFunc(craftList, 35645, 1);
    _getCraftListItems.InvokeFunc(craftList); // {}

```

**Expected behavior**
Following the call the Crafting menu should be refreshed reflecting the new values. The inventory highlighter should also update. 

**Dalamud Information:**
Do you have testing enabled? No

**Screenshots**
Here's how it looks in game. I'm triggering updates with /commands and logging the results to console.
[Kooha-2023-10-27-22-06-02.webm](https://github.com/Critical-Impact/InventoryTools/assets/30690931/66003bff-2040-49e2-99e6-159dfc88d866)

**Comment by Critical-Impact** [comment]
Fixed in the latest version
