### ISSUE TITLE
Exporting History Filters gives empty results for some columns

### ISSUE THREAD

**Issue by CitrusGender** [Critical-Impact/InventoryTools#232]
**Describe the bug**
Exporting History filters leaves some columns blank. Specifically the column "History Event Amount", "History Event Reason," "History Event Date/Time," and destination. Haven't tested anything else yet.

**To Reproduce**
1. Open up Atools
2. Create any History Filter with items populated.
3. Attempt to export to csv or Json

**Expected behavior**
Normally, I'd expect the history filter to give an amount. It does in the plugin but it doesn't 

**Screenshots**
Covered up some data just for my sanity but you get the idea.
![image](https://github.com/Critical-Impact/InventoryTools/assets/31262308/ed760435-2ff4-45f9-ba64-01ec9a4c8af3)

**Dalamud Information:**
Do you have testing enabled? No

**Filter Issues**
If you have an issue with a filter not working can you please export your filter configuration from settings and paste the export in the issue.

H4sIAAAAAAAACn1WXXPiNhSd/pMdPTMd/EHAvBHCFqabZROSpt1MH4R9A5rKkleWs8Nm8t97ZdnGxnIeGONzdL/kc6/02xt5oHsOm4TMSXAVJVezBPYBeGG89/f+ZBYCTGLw98EkmpIRWSr6os8W8TRKxp7n+Um4D2EczMBPJjCLgjGd+XFiLNbscOT407cyATIfj8hOFiqGjXgFoaVikJP5878jstGQPrIl1XCQ6mTc1+gOqIqPl8zqR8GyHZf6kijTW4OJSeZ+2E66h66BJqCWkmNOZP5G/sYMf8cc/zHPMIhG5DuZewZ5Kp/vVUZS9cLeQK6ZoJpJ0a8tX/8gc1Fwbv5jOA6xZpjQGVxlR0hBUV7m9YXlmOYL5TmMyFea4kJyS9V/oD89YJxPa+QxNu7vTZFxFmMu+VbwU+3vM+MalEk134h70JQJUJjMR+xKFCkWiS5ZnnF62gjcM7TRqsAkthmIRf7ERCJ/NpndFVRopjEswVQ2X+AVuP2/y5hiei9FYt9NDTasfbf/H04ZVuZdjcifYJzAyyyMUHJ+EHthkHhRDN7VDCaJNw0ibxqSWj0LzltV2QwbZi2LHJpiG/izAljKNKOCndlGnk9HEDX4mMP23mbIxKHnaHmkisa6Fbr17buZWcsu7cyju8RVwUbEvEhgqWSeNxk4zD9cZ2L/wui8SEV+ARrdXTAtt5Xc2WVafbxbSnuzKrujzHbAOW7tN8ViI21i0evi1AWt5Bev2BcH6OEPUlPeJ5dUXMO1LMpOr9tr8UoZNyNgoR9YCsnXchpZdvsTP5ZpY2zzTSxFTxtmPri22r2g/vymhzsEtpPbwswLpRuupTnLuEL2FrW9t8gGazn5iFulmennyvNBSAXrO9McZua1/DZj6gZeaMHP02rH0oxbNeFyO/XbgnmSiieNGMp11cBpTohGhc/l97Cv1RBpXqoRiPoSB1ikshDazd0DzVtOOtwNqrdhzDRqXurR1gCV3OvXLzK2fVED9We32iz12HDtPqoxu+5aUpXcMtFejweGqxmvpeRAhZ1LiL7hYVTKqIPstJlZHWgjsEWhu+wGYpZS3sEemdA9YHmUmFkX5lIcHLgN7SBaR9pbef4ZhWhI6vG5ZjivKrDRUb2f+MTp8gpbhSe1lYdxd0FTPHcGqW2hs0KXZ9uyUApEfPpDyQKnkLaSLi1POY6THv5NQWycdgn0tMKmO+kjvq4w355dnXbPrpztfwGeo6q9fn13D3ijUWZXqh2oRFDuCyqnaY+NOOAyhlcMTO4FTD1gtFvt0DPuMR7tHplP7G3Ftwp6HzUEpuEm/CEiGCJmQ0Q4GHyYMcW5mcH43mDK0aDJYPnThvDxqueCPTfsu+GZG554UeRkArzlBAM2/ng8aBO2mKvBsgflMO0SOH++SwFncdXCqgdTeXOsbrYOLba7vteLFWkCGDc9K0PgPcCJ38q9ez1eBMSACRPllcKdW8yyVpkVd+7EEkCkqt8bv/8PjGAW8DANAAA=

**Comment by CitrusGender** [comment]
@Critical-Impact If there's anyway I can help debug, let me know how. I've taken the last hour to look a little bit into how to debug ff14 mods but I can't see why this isn't rendering from a cursory knowledge of the code.

**Comment by Critical-Impact** [comment]
Fixed in the latest version
