### ISSUE TITLE
Curious Crop Exchange conversons are incorrect

### ISSUE THREAD

**Issue by Lii-Kun** [Critical-Impact/InventoryTools#234]
Curious Crop Exchange, aka trading voidrakes/Althyk Lavender for crafting mats, assumes 1 plant gets 1 of the mat but that is only true for some of them. Darksteel gives 3 for 1 voidrake. Cobalt gives 6.

Here are screenshots of the vendor. Set is how many you get for 1 plant. Qty. is how many is in your inventory.

![image](https://github.com/Critical-Impact/InventoryTools/assets/2645955/498f98ec-963e-4b62-a16a-7cd3d280f8e3)

![image](https://github.com/Critical-Impact/InventoryTools/assets/2645955/f7d31e39-4f71-4a37-a4e7-84646d6c59cd)

**Comment by Critical-Impact** [comment]
The numbers should be correct now, please reopen if this is not true(you'll need to update to latest version)

**Comment by Lii-Kun** [comment]
Correct numbers show for new lists made after update but old lists still use old numbers.
