### ISSUE TITLE
Can't give Alternate Names anymore

### ISSUE THREAD

**Issue by Ferikisekai** [Critical-Impact/InventoryTools#236]
On a previous version, it was possible to give characters, retainers and plots "alternate names" (like, for example, you could rename John Donovan simply JOHN, or rename a FC named Apple Store to just APPLE), but this feature completely disappeared and the only way to rename them now is by editing the file directly (and this is a nightmare to edit everytime since everything is in a single line).

**Comment by Critical-Impact** [comment]
Latest version restored this functionality
