### ISSUE TITLE
1.6.3.2 breaks plugin

### ISSUE THREAD

**Issue by Dajova** [Critical-Impact/InventoryTools#237]
**Describe the bug**
Update 1.6.2.3 completely breaks plugin and fails to load no matter what.

**To Reproduce**
-

**Expected behavior**
Should load without issue, no error.

**Screenshots**
![image](https://i.imgur.com/PTujo6o.png)

**Dalamud Information:**
Tested with and without. No difference.

**Filter Issues**
-

**Additional context**
Was fine earlier today, broke with the update, as explained.

**Comment by Critical-Impact** [comment]
Should be fixed now, was broken only on STG
