### ISSUE TITLE
AT now claims every MIN/BTN item is from ephemeral nodes

### ISSUE THREAD

**Issue by goldirocks** [Critical-Impact/InventoryTools#238]
**Describe the bug**
![image](https://github.com/Critical-Impact/InventoryTools/assets/32187006/c2030210-478f-4a7d-a288-89970b52e8a8)

This is on 1.6.2.5.

**To Reproduce**
Add literally anything that requires a gathering mat. I have not found any miner or botanist item that does not claim to be from an ephemeral node. (Fish do not seem to have this problem, presumably because they're a very different system.)

**Expected behavior**
Not to be told Copper Ore is an ephemeral node.

This is pretty inconvenient when you're world visiting and don't know which nodes you can or can't gather without memorization or opening the log for each.

**Screenshots**
![image](https://github.com/Critical-Impact/InventoryTools/assets/32187006/c2030210-478f-4a7d-a288-89970b52e8a8)

**Dalamud Information:**
Do you have testing enabled?
Yes, but I don't see a testing version of AT available, nor does it claim I'm using one.

**Additional context**

**Comment by Critical-Impact** [comment]
Fixed on latest release
