### ISSUE TITLE
Incorrect mob location

### ISSUE THREAD

**Issue by lwins-lights** [Critical-Impact/InventoryTools#239]
I found that 10% of mob coordinates from `/mobs` are incorrect. Is there any way for me to update them?
My conjecture is that the plugin does not correctly interpret integer coordinate data. For example, the second suggested coordinate for `U'ghamaro Priest` is `(2.2, 6.3)` while I found it at `(22.0, 6.3)` actually. Another case I found is that the `Sapsa Shelfclaw (1.5, 15.4)` is actually located at `(15.0, 15.4)`.

**Comment by Critical-Impact** [comment]
I've removed some bad data, this has reduced the total data pool a bit but it was really the only fix. One of the users has kindly provided their mob tracking data which has helped restore some of this.
