### ISSUE TITLE
"Duplicate List" results in the original list being empty

### ISSUE THREAD

**Issue by goldirocks** [Critical-Impact/InventoryTools#240]
**Describe the bug**
I attempted to duplicate a /crafts list, on 1.6.2.9.

After duplication, the original list was now empty.

**To Reproduce**
1) Open /crafts
2) Make a list of 1 or more elements to craft
3) Select that list
4) Right-click, "Duplicate List", input new list name, press enter
5) Original list still shows as having the original contents afterward
6) Click new list, new list shows same contents
7) Click old list, now displays empty contents

**Expected behavior**
The list was duplicated

**Screenshots**
N/A

**Dalamud Information:**
Do you have testing enabled?
No

**Comment by Critical-Impact** [comment]
Fixed in latest release
