### ISSUE TITLE
filters / inventory window blank

### ISSUE THREAD

**Issue by Ranzer1255** [Critical-Impact/InventoryTools#242]
**Describe the bug**
the filter window is a black blank box. 

**To Reproduce**
Open /inv or /filters

**Expected behavior**
see the existing filters and inventory lists

**Screenshots**
![image](https://github.com/Critical-Impact/InventoryTools/assets/5742529/5c78c42b-fe2c-494f-9e8d-57865ae524c6)

**Dalamud Information:**
Do you have testing enabled?
I do, but i'm unsure if i have a test build of aligan tools installed. 

**Filter Issues**
N/A

**Additional context**
running version 1.6.2.9 and dalamud shows no updates for the plugin:
![image](https://github.com/Critical-Impact/InventoryTools/assets/5742529/4e4e510e-9eba-4036-968b-12e7de6fa8c2)

also FC mate running the same version is having the same issue

**Comment by Ranzer1255** [comment]
additionally, all the other windows I've tried, such as settings, or the mob list. seem to be working as normal. it appears it's *just* the filters window

**Comment by Ranzer1255** [comment]
started digging some more and after sitting idle with the window open i suddenly CTD 
pulled up the log after logging back into game and saw this wall of Red text:

![image](https://github.com/Critical-Impact/InventoryTools/assets/5742529/808484db-dff7-486f-9c17-540800aa6df2)

**Comment by Critical-Impact** [comment]
This was a result of bug introduced on the STG branch of dalamud, should be fine but would definitely recommend sticking to stable if possible
