### ISSUE TITLE
Can not scan retainers' inventories and free company bag

### ISSUE THREAD

**Issue by Amarsimos** [Critical-Impact/InventoryTools#248]
**Describe the bug**
thanks for your wonderful work ,its a very nice plugin ,but when i try to find something in my retainers,it didn't work,and free company bag have same problem,by the way,I am using CN Client.Thanks for your help!

**To Reproduce**
1. Go to 'Data->Characters/Retainers->my retainer's name'
2. Click on 'my retainer's name'
3. it say "No inventories found"

**Expected behavior**
I should see my retainers' inventories

**Screenshots**
![image](https://github.com/Critical-Impact/InventoryTools/assets/48476733/73fc6a28-92f9-445c-ab53-efb8a4316d5a)
![image](https://github.com/Critical-Impact/InventoryTools/assets/48476733/fab16027-6e41-4fcb-b3ad-4fae2b391bfe)

**Dalamud Information:**
Do you have testing enabled?
yes

**Additional context**
here's xllogs when i open the plugin
21:12:46.361 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message ToggleGenericWindowMessage: WindowService
21:12:46.361 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message ToggleUintWindowMessage: WindowService
21:12:46.361 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message ToggleStringWindowMessage: WindowService
21:12:46.361 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message OpenGenericWindowMessage: WindowService
21:12:46.361 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message OpenUintWindowMessage: WindowService
21:12:46.361 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message OpenStringWindowMessage: WindowService
21:12:46.361 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message CloseWindowMessage: WindowService
21:12:46.361 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message CloseUintWindowMessage: WindowService
21:12:46.361 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message CloseStringWindowMessage: WindowService
21:12:46.361 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message CloseWindowsByTypeMessage: WindowService
21:12:46.361 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message CloseWindowsMessage: WindowService
21:12:46.361 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message OpenSavedWindowsMessage: WindowService
21:12:46.361 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message UpdateWindowRespectClose: WindowService
21:12:46.367 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message OverlaysRequestRefreshMessage: OverlayService
21:12:46.371 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message RequestTeleportMessage: TeleporterService
21:12:46.398 | INF | [InventoryTools] [       Lifetime]{2} Application started. Press Ctrl+C to shut down.
21:12:46.398 | INF | [InventoryTools] [       Lifetime]{2} Hosting environment: Production
21:12:46.398 | INF | [InventoryTools] [       Lifetime]{2} Content root path: D:\NEW\XIVLauncherCN\Roaming\pluginConfigs\InventoryTools
21:12:46.398 | DBG | [InventoryTools] [           Host]{1} Hosting started
21:12:46.431 | DBG | [InventoryTools] Inventory scanner does not have information about this retainer.
21:12:46.495 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message ListInvalidatedMessage: ConfigurationWindow
21:12:46.495 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message ListRepositionedMessage: ConfigurationWindow
21:12:46.495 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message ListAddedMessage: ConfigurationWindow
21:12:46.495 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message ListRemovedMessage: ConfigurationWindow
21:12:46.495 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message ConfigurationWindowEditFilter: ConfigurationWindow
21:12:46.495 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message ListInvalidatedMessage: ConfigurationWindow
21:12:46.495 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message ListRepositionedMessage: ConfigurationWindow
21:12:46.495 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message ListAddedMessage: ConfigurationWindow
21:12:46.495 | DBG | [InventoryTools] [MediatorService]{1} Subscriber added for message ListRemovedMessage: ConfigurationWindow
21:12:46.598 | DBG | [InventoryTools] [ OverlayService]{1} Overlays refreshing, active list: no list, background list: no list

**Comment by Critical-Impact** [comment]
I'm sorry but I don't support the CN version of the plugin, I don't know who supports it, and that's mostly down to the added work of supporting the correct hooks required to make the plugin function.

I would suggest opening a ticket with the person who maintains the CN version

**Comment by HirotaZX** [comment]
Hello, I have found the corresponding signatures for the CN 6.58 client and created a fork. However, I cannot guarantee that it will stay updated. I have listed the signatures I found here in case anyone needs them.
[HirotaZX/InventoryTools](https://github.com/HirotaZX/InventoryTools)

```
        //If the signature for these are ever lost, find the ProcessZonePacketDown signature in Dalamud and then find the relevant function based on the opcode.
        [Signature("E8 ?? ?? ?? ?? E9 ?? ?? ?? ?? 48 8B D6 8B CF E8 ?? ?? ?? ?? E9 ?? ?? ?? ?? 48 8B D6 8B CF E8 ?? ?? ?? ?? E9 ?? ?? ?? ?? 48 8B D6 8B CF E8 ?? ?? ?? ?? E9 ?? ?? ?? ?? 48 8D 56 10", DetourName = nameof(ContainerInfoDetour), UseFlags = SignatureUseFlags.Hook)]
        private Hook<ContainerInfoNetworkData>? _containerInfoNetworkHook = null;

        [Signature(
            "E8 ?? ?? ?? ?? E9 ?? ?? ?? ?? 48 8B D6 8B CF E8 ?? ?? ?? ?? E9 ?? ?? ?? ?? 48 8D 56 10",
            DetourName = nameof(ItemMarketBoardInfoDetour))]
        private Hook<ItemMarketBoardInfoData>? _itemMarketBoardInfoHook = null;
```
```
        [Signature("E8 ?? ?? ?? ?? F6 05 ?? ?? ?? ?? ?? 0F 85 ?? ?? ?? ?? 48 8D 56 10 8B CF E8 ?? ?? ?? ?? E9 ?? ?? ?? ?? 4C 8D 46 10 8B D7 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F6 05 ?? ?? ?? ?? ?? 0F 85 ?? ?? ?? ?? 48 8D 56 10 8B CF E8 ?? ?? ?? ?? E9 ?? ?? ?? ?? 4C 8D 46 10 8B D7 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F6 05 ?? ?? ?? ?? ?? 0F 85 ?? ?? ?? ?? 48 8D 56 10 8B CF E8 ?? ?? ?? ?? E9 ?? ?? ?? ?? 4C 8D 46 10 8B D7 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F6 05 ?? ?? ?? ?? ?? 0F 85 ?? ?? ?? ?? 48 8D 56 10 8B CF E8 ?? ?? ?? ?? E9 ?? ?? ?? ?? 4C 8D 46 10 8B D7 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F6 05 ?? ?? ?? ?? ?? 0F 85 ?? ?? ?? ?? 48 8D 56 10 8B CF E8 ?? ?? ?? ?? E9 ?? ?? ?? ?? 4C 8D 46 10 8B D7 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F6 05 ?? ?? ?? ?? ?? 0F 85 ?? ?? ?? ?? 48 8D 56 10 8B CF E8 ?? ?? ?? ?? E9 ?? ?? ?? ?? 4C 8D 46 10 8B D7 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F6 05 ?? ?? ?? ?? ?? 0F 85 ?? ?? ?? ?? 48 8D 56 10 8B CF E8 ?? ?? ?? ?? E9 ?? ?? ?? ?? 4C 8D 46 10 8B D7 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F6 05 ?? ?? ?? ?? ?? 0F 85 ?? ?? ?? ?? 48 8D 56 10 8B CF E8 ?? ?? ?? ?? E9 ?? ?? ?? ?? 4C 8D 46 10 8B D7 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F6 05 ?? ?? ?? ?? ?? 0F 85 ?? ?? ?? ?? 48 8D 56 10 8B CF E8 ?? ?? ?? ?? E9 ?? ?? ?? ?? 4C 8D 46 10 8B D7 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F6 05 ?? ?? ?? ?? ?? 0F 85 ?? ?? ?? ?? 48 8D 56 10 8B CF E8 ?? ?? ?? ?? E9 ?? ?? ?? ?? 4C 8D 46 10 8B D7 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F6 05 ?? ?? ?? ?? ?? 0F 85 ?? ?? ?? ?? 48 8D 4E 10", DetourName = nameof(NpcSpawnDetour), UseFlags = SignatureUseFlags.Hook)]
        private readonly Hook<NpcSpawnData>? _npcSpawnHook = null;
```
