### ISSUE TITLE
Issue with modifying required amout to craft

### ISSUE THREAD

**Issue by SpaceCadetAce** [Critical-Impact/InventoryTools#249]
**Describe the bug**
Unable to modify the value required for the To Craft output. I.e., an item like Baked Eggplant is stuck at 3 rather than being able to be modified to, say, 99 and the amounts needed to be gathered and/or precrafted being modified in turn. The box to input a new value can be selected, but only briefly, and the amount cannot be changed in that fraction of a second

**To Reproduce**
1. Go to Crafts menu
2. Add new item to be crafted (i.e. Baked Eggplant)
3. Go to change the amount in the Required column of the item's row
4. Amount cannot be changed and is stuck at whatever value is default

**Expected behavior**
Amount should be able to be modified, and has been in the past.

**Screenshots**
![image](https://github.com/Critical-Impact/InventoryTools/assets/172945069/f37af205-5685-46d8-874f-ccdaf4f397d7)

Bit difficult to show the bug via screenshots, but it should prove useful in showing what parts of the Crafts window I'm referring to

**Dalamud Information:**
Testing is enabled and everything is set to the Default configuration (fresh install of the plugin)

**Additional context**
It may be a simple issue of my configuration being messed up? I played FFXIV and used Allagan Tools on a different device (laptop) until recently, and had to re-install FFXIV and all my plugins when I got a new desktop PC; if I edited my configuration of my laptop, it would've been over a year ago and I have no idea how to replicate it

**Comment by Critical-Impact** [comment]
Do you have multiple copies of the "Required" column in your craft list? If so that'll probably break it.
If that does fix it, great, I'll still look into fixing the column and stopping duplicates from being generated
