### ISSUE TITLE
Allow aliasing retainer name

### ISSUE THREAD

**Issue by Nedlinin** [Critical-Impact/InventoryTools#25]
I was weird when I created my retainer and made their name almost identical to my character name. This makes the "Source" column a bit hard to deal with in the "All" filtering.  I'd love a simple Find/Replace style renaming for my retainer name if possible.

**Comment by Etupa** [comment]
get retainer fantasia from market board, you can change retainer's name with it :))

**Comment by Critical-Impact** [comment]
This should be possible in the upcoming testing version. Retainer Fantasia is definitely one way to do it but yeah if you need to rename them for whatever reason it's possible to do so(at least within the inventory tools plugin, I'm not touching the names in game)

**Comment by Critical-Impact** [comment]
Available in the latest live version.
