### ISSUE TITLE
Items in Retainers/Bags list not functioning

### ISSUE THREAD

**Issue by BLORTH1** [Critical-Impact/InventoryTools#250]
**Describe the bug**
The Items in Retainers/Bags list is not showing any items despite the items in retainers list working just fine.

**To Reproduce**
1. Go to crafts menu
2. Add any item to craft list
3. See error

**Expected behavior**
Available components for current crafting list that are located on retainers should be shown in "Items in Retainers/Bags" area. 

**Screenshots**
![image](https://github.com/Critical-Impact/InventoryTools/assets/173137964/8f460bb6-567e-4a40-9d1e-47d28c1c00ee)

**Dalamud Information:**
Do you have testing enabled? 
Yes

**Filter Issues**
If you have an issue with a filter not working can you please export your filter configuration from settings and paste the export in the issue.

**Additional context**
I might just be an idiot, but I've reset the plugin configuration to default, tried making new craft lists, uninstall/reinstalling the plugin, and I can't get the Items in Retainers/Bags list to be functional. I'm able to see my full item list for my retainers on the /atools menu. On the crafts screen itself it shows how many of each item is available.

**Comment by Critical-Impact** [comment]
Can you please post a picture of your "Inventories" tab inside the craft lists configuration?
