### ISSUE TITLE
Allagan Tools "crashing on clean install"

### ISSUE THREAD

**Issue by RayMPerry** [Critical-Impact/InventoryTools#256]
**Describe the bug**
So, I used AT last night to finish up some deliveries in Tuliyollal and logged out there. When I woke up this morning to finish the last one, Dalamud said that `this plugin has been automatically disabled: crash on clean install. Please wait for it to be updated by its author`. I can't possibly imagine what changed between last night and this morning especially when I didn't see an update in the launcher.

**To Reproduce**
1. Open the Dalamud plugins menu.
2. Observe that Allagan Tools is disabled with the above message.

**Expected behavior**
AT should be enabled.

**Dalamud Information:**
Do you have testing enabled? No

**Comment by Critical-Impact** [comment]
There was an update to AT that was causing crashes. It was banned so that people would not crash, a new update is currently in the plugin review queue and will hopefully be available soon.
