### ISSUE TITLE
Error After Dalamud Update, "Crash on clean install"

### ISSUE THREAD

**Issue by snowfi6916** [Critical-Impact/InventoryTools#257]
I am unable to use the plugin after the latest Dalamud update. I am getting the following error message.

"This plugin was automatically disabled: Crash on clean install. Please wait for it to be updated by its author."

Is there a fix planned for this? If not, what do I do to fix this?

![image](https://github.com/Critical-Impact/InventoryTools/assets/30598385/a41d6c90-449e-4dd2-b2e5-85f14d4ab2c8)

**Dalamud Information:**
No.

**Filter Issues**
Not a filter issue.

**Comment by xorcat** [comment]
Same here.

To be clear, this occurs multiple launches in a row - doesn't appear to be a fluke.

**Comment by xorcat** [comment]
Some kind of update was issued, and I don't have this issue anymore! Worth re-checking 😊
