### ISSUE TITLE
If using the Amount Owned - Search Locations option in the tooltips settings, it seems that retainers are being ignored

### ISSUE THREAD

**Issue by MikevLeeuwen** [Critical-Impact/InventoryTools#261]
I set the inventory scope as the following:
![Inventory Scope](https://github.com/user-attachments/assets/0406bbb7-a2f9-4eef-b03b-e8c7b653c2db)

After doing that and saving, I checked my retainers, but none of the items in there seem to be added to the tooltips. Saddlebags and regular inventory do work as intended from what I could see.
![retainer inventory](https://github.com/user-attachments/assets/6cbcc0ea-7acc-417e-b7f7-530ddd1aedc0)

**Comment by Critical-Impact** [comment]
Please give this a go now

**Comment by MikevLeeuwen** [comment]
Fixed! Thank you for the quick update!
