### ISSUE TITLE
Missing Bicolor Gemstone vendors

### ISSUE THREAD

**Issue by k0konoe** [Critical-Impact/InventoryTools#262]
**Describe the bug**
All Endwalker and Dawntrail monster drops associated with crafting do not appear to list any vendor source for bicolor gemstone purchasing, instead marked with repeated instances of 'unknown vendor.' I understand this may not be a problem for people who have maxed out shared FATEs, but such a task is time-consuming. 

**Screenshots**
Mousse flesh and megamaguey pineapple used as examples in these screenshots
![Screenshot_3248](https://github.com/user-attachments/assets/c17b95d5-0be0-4f66-b924-81d8d6ffa80a)
![Screenshot_3249](https://github.com/user-attachments/assets/f8ca7101-c6d2-4424-a111-3f952890e9d0)

**Comment by Critical-Impact** [comment]
These should show now, please reopen if they dont
