### ISSUE TITLE
Can't change number of items in the crafts tab

### ISSUE THREAD

**Issue by alex200qq** [Critical-Impact/InventoryTools#264]
**Describe the bug**
When you add a recipe to the list you can't change the number by typing, only by spam adding the same item to the list over and over again.

**To Reproduce**
1. Go to 'craft list'
2. Click on 'add item side bar'
3. Scroll down to 'the list and try to change the number of items'

**Comment by Wade821** [comment]
I would like to add that I had it work *once*, and then it went back to not working. It seems to be somewhat random with more tending towards not working more often than not.
