### ISSUE TITLE
Failed to Load

### ISSUE THREAD

**Issue by RenReo** [Critical-Impact/InventoryTools#265]
**Describe the bug**
Allagan Tools has been showing a "load error" every time I log in lately. 

**To Reproduce**
Nothing, I just log in to the game and it's not working

**Expected behavior**
I wanted it to work :(

**Screenshots**
![image](https://github.com/user-attachments/assets/f5bd8f06-1bae-4699-b871-ad7b478e9222)

**Dalamud Information:**
No 

**Filter Issues**
N/A

**Comment by crockcw** [comment]
I am also receiving the same error.  Is it just hit or miss or is there something we can do on our end to help prevent it?

**Comment by RenReo** [comment]
I clicked on the delete button while messing around yesterday. It wouldn't delete at the time but when I logged back in today it was gone from my installed plugins and I could reinstall it back to working order.

**Comment by Adnade** [comment]
I may be wrong, but deleting and reinstalling it doesn't seem to make a difference. Sometimes it works, sometimes it doesn't. Sometimes it works at first, then apparently splats at some point later. Even after reinstalling, it appears to eventually asplode no matter what you do, so waiting on Dalamud to fix this may be the only option.

**Comment by Critical-Impact** [comment]
Still waiting on dalamud to resolve this, they appear to be delaying a release because they are trying to get reshade/gshade related things sorted.
Due to the nature of the bug, whether or not it breaks seems to be fairly random, you might load sometimes, you might not.

**Comment by Critical-Impact** [comment]
If you were having issues please try updating your dalamud and see how you go. If you cannot load still, post your dalamud.log

**Comment by RenReo** [comment]
Seems to be working now!

**Comment by Critical-Impact** [comment]
The update for dalamud is only on staging atm
You can switch to that if you are having issues or wait for a full release
It's possible you might already be on STG
