### ISSUE TITLE
Allagan Tomestone of Aesthetics are not being tracked

### ISSUE THREAD

**Issue by GayPotatoEmma** [Critical-Impact/InventoryTools#270]
**Describe the bug**
AT does not appear to be tracking Allagan Tomestones of Aesthetics

**To Reproduce**
1. Have Aesthetics tomestones
2. Either make a crafting list that needs items bought with those tomestones or just check an item list of your inventory
3. (optional) filter by searching for `tomestone`

**Expected behavior**
The Allagan Tomestones of Aesthetics should be tracked just like the other tomestones

**Screenshots**
![image](https://github.com/user-attachments/assets/3e713848-2c2a-4113-8a21-89f1e9e826d5)
![image](https://github.com/user-attachments/assets/55777347-19de-4f2a-8a51-2750f62e05ea)

**Dalamud Information:**
Do you have testing enabled? No

**Filter Issues**
If you have an issue with a filter not working can you please export your filter configuration from settings and paste the export in the issue.

**Additional context**

**Comment by Critical-Impact** [comment]
Appears to be working in the latest version
