### ISSUE TITLE
Sales Tracking?

### ISSUE THREAD

**Issue by afairgiant** [Critical-Impact/InventoryTools#272]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. Would it be possible to track the item sales from retainers, basically like a ledger.

**Describe the solution you'd like**
Have a page that says in X time frame, i have sold x number of this item for this amount. Or just a running list of sales from all my retainers.  I think the data should be able to be pulled from the retainers sale history. 

**Describe alternatives you've considered**
This is partially available in Teamcraft, but it doesn't show individual items, just total Gil changes.

**Additional context**

Here's an old example from an wow addon called TSM that shows a sale history.
![image](https://github.com/user-attachments/assets/88b45806-1b86-433c-b882-134030da3fc0)

**Comment by Critical-Impact** [comment]
Please give Allagan Market a go, it should do basically what you've requested
