### ISSUE TITLE
Sort gatherables by zone

### ISSUE THREAD

**Issue by d07RiV** [Critical-Impact/InventoryTools#278]
**Is your feature request related to a problem? Please describe.**
Is there a way to show gathering zone and/or sort items by the zone (in the crafting list)? It would save a fair bit of teleports if we could go through all the items in a single zone first instead of teleporting back and forth.

**Comment by Critical-Impact** [comment]
Edit your craft list's configuration and set "Group Everything Else By" to "Zone"
Gatherables will then be grouped by zone
