### ISSUE TITLE
ran into a error

### ISSUE THREAD

**Issue by dex44801** [Critical-Impact/InventoryTools#28]
i switched form one charakter to antoher and since then, the plugin says it runs into a error.
Restart the game and reinstall the plugin doesnt work. 
Even if i delete the folder nothing changed.

It is a great Plugin so maybe you can help :)

**Comment by Critical-Impact** [comment]
Hi just wondering if you have seen this happen again? If not I will close, if you have can you please try to get a log the next time it happens.
