### ISSUE TITLE
Craft button only works for first item on the list

### ISSUE THREAD

**Issue by vexis58** [Critical-Impact/InventoryTools#282]
**Describe the bug**
When a crafting list has multiple craftable items, the button in the "Craft Button" column only functions for the first item on the list. Clicking the button for any other item does nothing.

**To Reproduce**
1. Add multiple crafting items to a list that has the "Craft Button" column added.
2. Click the Craft button for any item below the first one.

**Expected behavior**
Crafting Log opens to that specific item.

**Screenshots**
![image](https://github.com/user-attachments/assets/8756fa72-6c9e-4bca-a323-a466e90f43d1)

**Additional context**
This was working properly several days ago, but stopped working recently.
Gather button still works properly.

**Alternate Approaches**
Right-clicking on the items and selecting "Open Crafting Log" still functions as expected.

**Comment by Critical-Impact** [comment]
Fixed in the latest version
