### ISSUE TITLE
Furymint is not marked as a timed node

### ISSUE THREAD

**Issue by Nitrousoxide** [Critical-Impact/InventoryTools#283]
**Describe the bug**
Furymint is not marked as timed, despite being so:
https://ffxiv.consolegameswiki.com/wiki/Furymint

**To Reproduce**
1: Add recipie that requires furymint
2: Furymint is not marked as timed

**Expected behavior**
Furymint should be marked as timed

**Screenshots**
![image](https://github.com/user-attachments/assets/78b3d1d1-dd43-443a-bf22-c7affc49a375)

**Dalamud Information:**
No

**Filter Issues**
N/A

**Additional context**
None

**Comment by Critical-Impact** [comment]
Fixed in latest version
