### ISSUE TITLE
Glamour Chest not tracked since 7.1

### ISSUE THREAD

**Issue by YsEmei** [Critical-Impact/InventoryTools#286]
**Describe the bug**
I've added two items in Glamour Chest and they don't show up in the item tooltip as being in the Glamour Chest.

**To Reproduce**
1. Put an item in Glamour Chest
2. See how it still says it's in your bag if you view the item's tooltip.

**Expected behavior**
Shown to be in Glamour Chest and no longer in your bags.

**Screenshots**
![image](https://github.com/user-attachments/assets/c5a07b9d-976f-4d6d-be1f-916ec35a28bb)

**Dalamud Information:**
Dalamud Release v11.0.0.0

**Comment by Critical-Impact** [comment]
Should be fixed if you update to the latest version
