### ISSUE TITLE
Whitespace and non-alphanumeric characters in crafting search box result in no results

### ISSUE THREAD

**Issue by Nitrousoxide** [Critical-Impact/InventoryTools#287]
**Describe the bug**
I am unable to search for the full names of items which have non-alphanumeric characters in them.  I can only search up to the last "regular" letter.  

Example:
Common searches fine:
![image](https://github.com/user-attachments/assets/df6d5c08-97e4-4754-981a-cb6c86710b85)

"common Makai" does not
![image](https://github.com/user-attachments/assets/b1ffd678-5567-4180-95df-f1c7e29fad6b)

There are plenty of common makai items: example:
https://ffxiv.consolegameswiki.com/wiki/Common_Makai_Harbinger%27s_Battlegarb

**To Reproduce**
1. Open up the /crafts window
2. Go to a craft a craft list
3. Click the magnifying glass icon to search
4. Enter in name with whitepsace or non-alphanumeric characters (spaces, hyphens, etc)
5. Get no search results

**Expected behavior**
The search should continue to drill down with more detail

**Screenshots**
See above

**Dalamud Information:**
Do you have testing enabled?

**Filter Issues**
If you have an issue with a filter not working can you please export your filter configuration from settings and paste the export in the issue.

**Additional context**

**Comment by Critical-Impact** [comment]
Fixed in latest version
