### ISSUE TITLE
Dark Chestnut is marked as a timed node

### ISSUE THREAD

**Issue by ihadarms** [Critical-Impact/InventoryTools#288]
**Describe the bug**
Dark Chestnut is marked as timed, despite being hidden, but not timed:
https://ffxiv.consolegameswiki.com/wiki/Dark_Chestnut

**To Reproduce**
1: Add recipie that requires Dark Chestnut
2: Dark Chestnut is not marked as timed

**Expected behavior**
Dark Chestnut shouldn't be listed as a timed node.

**Screenshots**
![image](https://github.com/user-attachments/assets/ee217b23-5973-479d-b967-922485a6fbd2)

**Dalamud Information:**
Do you have testing enabled?
Yes, but it isn't enabled for Allagan Tools.

**Filter Issues**
N/A

**Additional context**
N/A

**Comment by Critical-Impact** [comment]
Fixed in latest version
