### ISSUE TITLE
Unlock Status will show even when disabled

### ISSUE THREAD

**Issue by ZyRage** [Critical-Impact/InventoryTools#291]
**Describe the bug**
The Unlock status of minions and other unlockable items are shown in the tooltip for all chars even when it's disabled in the settings

**To Reproduce**
Set "Add Item Unlock Status" under Tooltips to disabled
Check the Tooltip of any unlockable item like a minion 

**Expected behavior**
No information in the Tooltip if this is aquired or not on any char.

**Screenshots**
https://prnt.sc/QzDAoIyJy5IJ

**Dalamud Information:**
Do you have testing enabled?
Yes

**Comment by Critical-Impact** [comment]
Fixed in current build
