### ISSUE TITLE
Background filter defaults to All for fresh install

### ISSUE THREAD

**Issue by SnoFox** [Critical-Impact/InventoryTools#30]
It appears the settings for removing or changing the retainer color/item count on the summoning bell list does not respect the "Retainer Visuals" panel of the configuration.

Additionally, when I exit the Inventory Tools UI, it appears every item matches the filter, leaving my inventory and retainers highlighted.

Video here until issue acknowledged: https://snofox.net/share/Screenshot-ARCTIC-2526.mp4

**Comment by Critical-Impact** [comment]
Turn off your background filter in settings.
The plugin has a foreground filter(when the UI is open) and a filter for when it's closed.
If you didn't change the background filter I do need to look into why it defaulted to using one but yeah that should stop it.

I'm going to come up with a better way to handle this when I get some time

**Comment by SnoFox** [comment]
Thanks for looking into this.

It did indeed default to these settings, I didn't change them (at least, intentionally.)

After turning off the Background filter, this is no longer a problem. I'll update the description accordingly.
