### ISSUE TITLE
Inventory is completely highlighted when the /inv window is not open (checkbox doesn't change anything)

### ISSUE THREAD

**Issue by TheMangoFuture** [Critical-Impact/InventoryTools#32]
This has persisted through restarting the game and disabling/re-enabling the plugin. It happens consistently no matter what. As long as the /inv window is open nothing is highlighted. As soon as I close it, my entire inventory highlights green.

I'll attach a gif of it happening to this post

https://media.giphy.com/media/LowLzSIt7xj2CmfEZa/giphy.gif

**Comment by Critical-Impact** [comment]
Go into inventory tools settings -> general and turn off the background filter.
You have 2 filters, one for when the inventory tools is visible and one for when the inventory tools window is closed. The background filter can also be manipulated with slash commands which you can find in the help section of the inventory tools window.
Once you set your background filter to none the highlighting should stop.

**Comment by TheMangoFuture** [comment]
> Go into inventory tools settings -> general and turn off the background filter. You have 2 filters, one for when the inventory tools is visible and one for when the inventory tools window is closed. The background filter can also be manipulated with slash commands which you can find in the help section of the inventory tools window. Once you set your background filter to none the highlighting should stop.

This did it! Thank you so much - I love this plugin but the highlighting was driving me bonkers lol. Cheers :)
