### ISSUE TITLE
Pressing Left Trigger on controllers causes frame drops.

### ISSUE THREAD

**Issue by GokaiSanyu** [Critical-Impact/InventoryTools#33]
I've been noticing framerate drops in my name as of late, and after confirming the issue was within Dalamud, I narrowed it down to two plugins, one of them being InventoryTools. I THINK it may have something to do with L2 being the button to check HQ/NQ (depending on what quality the item already is), but I have no way to confirm if it's that.

**Comment by Critical-Impact** [comment]
So I hooked up a xbox one controller and have opened my inventory, selected an item and pressed L2. I see the tooltip switching between NQ and HQ, though I don't get any noticable lag.
Have you had a look in the /xldev log to see if anything comes up when you press L2?
Definitely want to help you out, just haven't been able to replicate so far.

**Comment by nickXIII** [comment]
Just chiming in to second this issue. I haven't checked the log, but for me it happened when holding L2 while in the final dungeon and trial of EW. I haven't noticed the issue elsewhere.

**Comment by Critical-Impact** [comment]
If you could get a log or a way you can get this to happen outside of a dungeon I would definitely have an easier time replicating it
Which controller are you using btw?

**Comment by nickXIII** [comment]
I also noticed the issue while Fate farming in Rak'tikayesterday, but it
was far less prevalent. I use a Dualsense controller. As for the logs,
where are those located? I'll try and get one over to you.

**Comment by RIot13** [comment]
Can confirm, narrowed down my plugins too, On k&m, it happens when you press Ctrl.

**Comment by Critical-Impact** [comment]
Hey still trying to work this one out, if you could do these things it'd really help me get to the bottom of it.

Can you please take a screenshot of your general configuration screen and also let me know if you
1) Have the main window open at the time
2) Have a filter active or not
3) Is it hitting control at any point or is there some specific point at which control starts to make it lag
4) In your FFXIV game settings, is CTRL bound to something and if so what is it?

**Comment by RIot13** [comment]
![image](https://user-images.githubusercontent.com/24972521/151659755-f074da85-9c5d-496c-b9ef-585bf935dbdb.png)

Ok after deleting all my filters and restarting the game, this bug only starts after you open your inventory. From thereon, it still affects while your inventory is closed. Ctrl + 1-9 are bound to my aoe spells hotbar. By default ffxiv ctrl is bound to check HQ/LQ items.

While holding Ctrl, the fps drops steadily till 50 and goes back to normal after releasing the button.

**Comment by Critical-Impact** [comment]
Appreciate it, while my game does not lag when the button is pressed I can see an error happening when the key is hit.
I'll put out a fix in the next testing release and hopefully that does the job :)

**Comment by RIot13** [comment]
Sweet, tyvm.
