### ISSUE TITLE
[Bug] Highlights the empty slots

### ISSUE THREAD

**Issue by Spazzze** [Critical-Impact/InventoryTools#34]
Hi! First of all thanks for your work!

I got an issue today. 
My filter is set to duplicates only and today it began to highlight the empty slots, very uncomfortable to use. How I can fix this? I tried to remove all InventoryTools files from XIVLauncher\pluginConfigs and got like fresh install and after enabling the "Duplicates only" the same problem appeared.

![image](https://user-images.githubusercontent.com/8989548/150681413-e7f44afb-5617-4298-bca8-d5462696e4ba.png)

![image](https://user-images.githubusercontent.com/8989548/150681092-635ab419-6a1f-4dcb-9daf-2cc660c93ca0.png)

This is my filter. All I need from this filter is to highlight duplicates which I need to put to the retainer. 
![image](https://user-images.githubusercontent.com/8989548/150681553-3f62b30e-ea28-498c-a96a-b22e04d273bf.png)

**Comment by Critical-Impact** [comment]
Have been able to replicate, will include a fix in the next build

**Comment by Spazzze** [comment]
thanks!
