### ISSUE TITLE
“Unknown” after in-game trade

### ISSUE THREAD

**Issue by l-moon-git** [Critical-Impact/InventoryTools#41]
I am a bit new to submitting issues, so bare with me. I am experiencing a bug with the plugin where after I trade with someone if we both have the same item in our inventories it will register as “Unknown” under inventory locations. I can clear out plugin config and it reverts, but Thought I would bring it up as a issue just incase I’m not the only one.

**Comment by Critical-Impact** [comment]
Definitely been seen, will see if I can get a hotfix out specifically to address this as the mass of changes I want to get out in the next release are taking longer than I thought they would.

**Comment by l-moon-git** [comment]
It’s all good, no rush. If there is something I can do let me know. ^.^

**Comment by Critical-Impact** [comment]
Closing, this should not happen anymore in either the live version/testing version. Reopen if it does
