### ISSUE TITLE
[suggestion] Highlight items in Chocobo Saddlebag

### ISSUE THREAD

**Issue by chalkos** [Critical-Impact/InventoryTools#42]
In my specific case, background filter highlighting on the Chocobo Saddlebag when I'm at a retainer (use hotkey to show, default ctrl+shift+I), so I can see which items are duplicated between retainer <-> saddlebag

**Comment by Critical-Impact** [comment]
This should be functioning, can you let me know if it's not

**Comment by chalkos** [comment]
It's working. I needed to add the saddle as a source for it to work, so I don't know if you actually added this or if it was already there when I created the issue. In any case, thank you!
