### ISSUE TITLE
[bug] retainer duplicate items background filter showing when not at a retainer

### ISSUE THREAD

**Issue by chalkos** [Critical-Impact/InventoryTools#43]
It was working until I figured that I probably never want to use inverted highlighting so I toggled it off in general, and also like the colors i chose for the duplicates so I changed them in general as well.

This made it so that my background filter to show duplicates (set to only show at retainers) now shows everywhere, even when I'm not at retainers.
I compared my duplicates filter to the preset duplicates filter and they were similar. I then changed my background filter to the preset duplicate filter and it still kept being shown when I'm not interacting with the retainer bell.

Mu config without my items:
[InventoryTools.json.txt](https://github.com/Critical-Impact/InventoryTools/files/8541069/InventoryTools.json.txt)

**Comment by chalkos** [comment]
I had a backup of my configuration:
[InventoryTools.json.old.txt](https://github.com/Critical-Impact/InventoryTools/files/8541265/InventoryTools.json.old.txt)

so I disabled the plugin, and coppied the config part from this old file into the current one (without touching the items part).

This did not fix the problem. So it's either a problem with a recent version or it will disappear when I restart my game.

As the config shows I also added a new filter. I wonder if that changed something outside of the plugin. something that would survive a plugin disable -> config change -> plugin enable.

**Comment by chalkos** [comment]
As another test, I disabled the plugin, coppied over the entire old config (emptying inventory data as well), then enabled the plugin and set the background filter to the duplicate items.

opened inventory: no highlight (as it should since it has no inventory data other than my inventory)
opened retainer inventory: highlighted (as it now knows about the duplicate item i have in both my retainer and my inventory)
stopped interacting with the retainer bell and openned inventory: still highlighted (bug)

**Comment by chalkos** [comment]
Restarted the game and it still happens. so I guess it's not the plugin changing something it shouldn't.

**Comment by Critical-Impact** [comment]
So do you have the background filter on at all times? If so it's going to highlight everything duplicated
The toggle "Filter Items in Retainers" will only trim the list down when you are inside a retainer.
At present the plugin will not tweak how items highlight based on conditions(well not yet anyway)
Let me know if that doesn't make sense

**Comment by chalkos** [comment]
That's odd... I could swear it was not showing... but maybe that's because the background filters always get disabled, and so I'd enable them at my retainers and after that I wouldn't have any duplicates.
Seems like I made up a feature and went on quite a wild-goose chase there.

Closing since this one was all in my head 😅
