### ISSUE TITLE
Lowest price for Market Board prices

### ISSUE THREAD

**Issue by lsequeiraa** [Critical-Impact/InventoryTools#45]
The tooltip with MB info on the items is incredibly useful. Unfortunately, the average price is not usually a good indication of the price of the item, due to people sometimes having orders with incredibly high prices. While a good pointer, I think a minimum price would also be important information.

If possible, an option to see the lowest price on the current Data Center would be incredibly useful, for example, when judging a quest reward, to see which would be best to take to sell in the MB.

**Comment by Critical-Impact** [comment]
This is available in the testing release, let me know how it goes if you have testing otherwise you'll need to wait for this to become a full release.

**Comment by Critical-Impact** [comment]
Closing as it is in the latest released version.
Still looking to add more ways to compare items against the market so keep an eye out for that
