### ISSUE TITLE
Numeric condition fields seemingly treated as strings

### ISSUE THREAD

**Issue by PrincessRTFM** [Critical-Impact/InventoryTools#48]
Several of the numeric condition fields, such as quantity and the marketboard prices, are apparently being treated as string fields, and aren't accepting inequalities such as `<10` for fewer than ten of an item. I have a filter that highlights Icarus Wings among other things, of which I have 105. If I add `<200` in the quantity condition field, no items _anywhere_ are matched by the filter. If I simply write `5` in the field, only items with a quantity _containing_ the digit `5` are matched.

**Comment by Critical-Impact** [comment]
Should be good in the latest version
