### ISSUE TITLE
[Request] Housing Storage?

### ISSUE THREAD

**Issue by gucciBane** [Critical-Impact/InventoryTools#49]
Is it possible to search storage across your houses? This is the hardest thing to keep track of for me, and would be incredible.

Stuff's awesome, thanks so much!

**Comment by Critical-Impact** [comment]
It should be possible but there are some complexities to it so might be a while before I can make this happen.
Maybe in the next month?

**Comment by gucciBane** [comment]
It would be great even as something to look forward to :)

**Comment by Critical-Impact** [comment]
This is now implemented in the latest version
