### ISSUE TITLE
Inventory Tools Window is empty

### ISSUE THREAD

**Issue by Imaginary-Narwhal** [Critical-Impact/InventoryTools#55]
Upon installing the addon, my wife's Inventory Tools is completely empty. On my game it works just fine. Is there a setting, or some advice you can give as to why her's won't populate? Is there a log that maybe the plugin is working to an extent that I can look into?

**Comment by Critical-Impact** [comment]
Hi, was this sorted in testing? I saw that I was tagged but have not had the time to respond yet.
If no, please just delete the "All", "Retainer" and "Game Item" filters and recreate them. The other option if you are a new player is to disable the plugin, delete the config and reload the plugin(I will add an easier way to do this in the future)

**Comment by Critical-Impact** [comment]
Closing as this should be fixed
