### ISSUE TITLE
Wrong sorting order on retainers

### ISSUE THREAD

**Issue by zandzpider** [Critical-Impact/InventoryTools#57]
![image](https://user-images.githubusercontent.com/321691/166933407-57dc1298-7339-48c5-93c7-0c2eaae9fb81.png)

**Comment by Critical-Impact** [comment]
I will see what I can do, the order they use in game is not entirely clear to me and I thought I had it mostly worked out but apparently not.

**Comment by zandzpider** [comment]
How did you find out the current order? i looked at your function and it looks reasonable but hard to find out what they actually do in game. i can test it when you got something

**Comment by Critical-Impact** [comment]
It was mostly a combination of examining the order that was shown when I put items up and then ordering the items by attributes the items share.
The image you've posted will be helpful as I can use it to create a test case and then start altering the function to see if I can get the order corrected.
I'll keep you up to date/watch the changelogs for when I update the function that calculates the order

**Comment by Critical-Impact** [comment]
Believe I've sorted this one, will be in the next test version.

**Comment by zandzpider** [comment]
Ooooh well done! Makes me wonder what you did and how much time you used

**Comment by Critical-Impact** [comment]
Let's just say my original solution took far longer and tried to be overly clever when I could have literally sorted by 3 things and had the correct order.
Though it did help me build out a testing framework for the plugin so I can make sure these sort of things continue to work.

**Comment by Critical-Impact** [comment]
Should be good now
