### ISSUE TITLE
Filter Column - Total Quantity Across Source

### ISSUE THREAD

**Issue by SubaruYashiro** [Critical-Impact/InventoryTools#60]
Owned from Tooltips as Columns in Filter

**Comment by SubaruYashiro** [comment]
Basically, I gathered X (and X is crafting items), currently in my inventory, i have around Y amount. But, in total, i actually have Y + Z (since Z is from other source). The Total Quantity is the new Column i would like to have

**Comment by SubaruYashiro** [comment]
Oh, actually, this is already implemented but as Tooltip, Owned Section.
so Owned from Tooltips as Columns in Filter

**Comment by Critical-Impact** [comment]
There is a new column available called "Quantity Available" in the live version. Please open a new issue if you run into any bugs with it.
