### ISSUE TITLE
Default "highlighting" in Armory chest is broken after using Sort

### ISSUE THREAD

**Issue by jjspace** [Critical-Impact/InventoryTools#61]
After one of the more recent updates, maybe even the one that added the Armory chest, I noticed that the default dimming of gear was being turned off. This is happening even if you don't have the `/inv` window open or a background filter applied.

Reproduce:
1. open the armory chest
2. Take note that all gear you _can't_ equip is dimmed making it easy to identify gear you might want to equip
3. Right click and hit Sort (or use the button on controller I assume)
4. Notice that there is no gear dimmed anymore, it's all full color which makes it hard to know what you can equip
5. switch to a different tab of the armory chest
6. switch back to the first and see the dimming has returned as expected (this is the work-a-round I've been using)

**Comment by Critical-Impact** [comment]
I was being a bit overzealous with when I "cleared" the game UI. It should only apply the highlighting when you actually have a filter or turn a filter off. This does mean that if you apply a filter, turn it off and then sort you might still not have the game highlighting applied but if you then just close the armoury chest and reopen the correct highlighting will show.

This will be in the next test release.

**Comment by Critical-Impact** [comment]
Fixed in the latest live release, please open a new issue if you run into further issues.
