### ISSUE TITLE
Option to add Character Name to Retainer-Source?

### ISSUE THREAD

**Issue by Shuro** [Critical-Impact/InventoryTools#62]
Back in the days I created my retainers with no plugins in mind, so they have random names I can't keep track of.

While searching items across my characters, it would be nice if there was an option to have it look like this:

### Source
Character Name 1
Retainer Name 1 (Character Name 1)
Retainer Name 2 (Character Name 1)
Character Name 2
Retainer Name 1 (Character Name 2)
Retainer Name 2 (Character Name 2)
Character Name 3
Retainer Name 1 (Character Name 3)
Retainer Name 2 (Character Name 3)

**Comment by Critical-Impact** [comment]
This is available in the latest live version, in Configuration -> Visuals -> Tooltips there is an option called "Add Character Name to Owned?"
