### ISSUE TITLE
Small bug: Highlight? has a scroll bar

### ISSUE THREAD

**Issue by Imaginary-Narwhal** [Critical-Impact/InventoryTools#66]
The field that holds the highlight checkmark on any of the tabs has a scrollbar on it. Just a small cosmetic bug. Also clicking the "open" button next to Found a bug? does nothing.

**Comment by Critical-Impact** [comment]
Thanks for the report :)
It was related to not scaling based off the user's global font scale.
Have also fixed the button.
Will be in the next testing version.

**Comment by Critical-Impact** [comment]
Should be in the latest live version
