### ISSUE TITLE
Source/destination categories broken

### ISSUE THREAD

**Issue by PrincessRTFM** [Critical-Impact/InventoryTools#68]
Source inventory categories has "bags" listed twice, and with the following configuration, I'm unable to _remove_ any categories from the source category list or the destination one. Additionally, it doesn't seem to actually be filtering them, because even with this filter, I'm still seeing items being filtered from my glamour dresser, which isn't enabled. Likewise, some items are being filtered from market sales, which is also not enabled.

> `H4sIAAAAAAAACn1TTXPaMBCd/hWdfcDGMNQ3MM3EU0LaQCaHTA6ytcaaCsmRZDI0k//eNUIOrmkPntG+5/18u1/eyZbmAjJGEpKX4WgyicbAphDDhOVFBHE5K8dsxsK8yElA1gDMPECpwVQksbqBgNzyXSXws3eKAUlGAdmoRheQyQNIqzQHQ5Lnl4BkFvaPPKUWdkof25Qe3QDVRfU38+214fVGKHvVRekBvgRjuaSWKzlMbm5fSSIbIdp3qoSAwnJs3YNrusc3WTY1umCspha8wATmXoqj7/WGCwu6zW8y+QCWcgnaeHbJTS3oMZM40w68r0HOzROXTL2RpKTCIPizodJyi3EJ5spWcADh3puaa25zJVtFiCvLZXW2e2+PNRYbBeQ7tDHiaFxG05yG4fRrTFlIo2ga5rMZGxfxqJjGxGsyF2JQdaffUwXST6P7Pa2opoW97PJzytfCefEL0TBItTKmC+GD93T6z383GuA3oFbNXporzmf9ncZxEAZRMHvxFfyD7Fd/2d258UrVGxCCy90PzYt2JYhDF82xD95R/Qvs/ACa7mCAb5WlYkimVC5goRqc9+c6zg+Ui/YO53bL98DWp0ty7P0bTrfdcDysrFCdQp1sOB/VjczLseKmT+BKXvdoL0XbjsMW+8yl4wXZqfJ8qsqZ531NvdGuaWf4ne+As07eXCk8t1ZVD1wq7TDUb6GUACrdGWD6949TLUr3kI3VWGsPyiTuA/R/e+TSDoC0UqhWHxZK7q7gLs2A+PgDR/h6bFcFAAA=`

**Comment by Critical-Impact** [comment]
Appreciate the filter export, I believe I've fixed the issues I can see.
One thing I should point out is that the inventory selection is additive. So if you select just "Bags" and "Retainer Bags" for your inventory categories then select "All Retainers" and "All Characters" that'll include all the bags from all retainers and all characters.

I can understand why you configured the filter the way you did and I think I'll need to consider reworking how parts of the source and destination selection work as I think the assumptions you made about how it work are reasonable.

So either I need to make it more specific as to what inventories will be selected or make it easier to pick exactly what you are after.

**Comment by PrincessRTFM** [comment]
In case more detail helps, I'm trying to include all of my "standard" inventories where I end up with stuff lying around. My armoury chest is pretty well kept clean, and I often don't want to market _everything_ of an item type (especially since I hold onto HQ but usually sell NQ), and my FC uses part of our company chest for junk drawers. My glamour dresser and armoire are long-term storage and only need one of an item in them, so I don't care about putting duplicates away in there and I don't want to take any out.

In the end, my inventory, my saddlebags, my retainers' inventories, and my FC chest is pretty much all I wanted for that particular filter.

**Comment by Critical-Impact** [comment]
This should be fixed in the latest live version, please reopen/open a new issue if it's not
