### ISSUE TITLE
[Request] add in Sort Filter, `Option to highlight both the source and the destination on Sort Filter, rather than just the source

### ISSUE THREAD

**Issue by SmoothJaz** [Critical-Impact/InventoryTools#70]
Currently if you want to use Inventory tool to check for duplicate items across inventories it will only highlight the source, but when youre trying to find out where that item is in the destination theres no indication as to where that duplicated item is.

for example if i have some iron ore (which has a sprite that multiple items use) in the destination and the source but the destination is a mess of items randomly strewn around. i cant see clearly where the iron ore needs to go because while i can see where the iron ore is in my inventory (the source) i still dont know WHERE the other stack of iron is in the company chest that i need to drag the item to. 

I rarely use github and dont really understand a lot of it lol so sorry if theres a format that i didnt see, and arent adhering too...  

(added an image to help illustrate what im trying to say)
![Screenshot 2022-05-15 024132](https://user-images.githubusercontent.com/69060834/168440875-3181766e-7442-4fc2-bd67-01dc64b76b47.png)

**Comment by Critical-Impact** [comment]
The plugin now has destination filtering which should be enabled by default. When sorting, it should show the source items in one colour and the destination in another(these are configurable).
Please open a new issue if you find any bugs :)
