### ISSUE TITLE
Wrong sort order on market items

### ISSUE THREAD

**Issue by zandzpider** [Critical-Impact/InventoryTools#71]
Item in question is "Necklace Display Stand" and "Restaurant Showcase"

![image](https://user-images.githubusercontent.com/321691/168629044-e44071eb-29a9-4d7f-9bd6-33f93ea4ff74.png)

**Comment by zandzpider** [comment]
Been struggling with tabletop items in general. don't know if that means anything

**Comment by Critical-Impact** [comment]
Thanks for the report, the specific case you've provided is an extra thing for me to add to my unit testing, will add it in and see if I can work out what I'm missing.

**Comment by Critical-Impact** [comment]
Reopen if you have further issues, should be in both live and testing now.
