### ISSUE TITLE
Retainer inventory items not being displayed

### ISSUE THREAD

**Issue by HQuest** [Critical-Impact/InventoryTools#78]
First time installing this plugin. None of my retainers' inventory items are displayed. I can see the plugin recognizing the retainer as it updates the "Configuration > Characters/Retainers > Retainers" name with the last retainer I've open its inventory. However, the Retainers tab continues to be empty. Also, under "Configuration > Retainers > Inventories", it only displays one retainer name under "Retainer Sources", and I expected to see all of my retainers.

**Comment by Critical-Impact** [comment]
Opcodes are currently incorrect which is most likely breaking retainer parsing. I'll add a comment in here once they are good.
