### ISSUE TITLE
Tooltip text for equipment are colored red/green

### ISSUE THREAD

**Issue by DenL** [Critical-Impact/InventoryTools#79]
Tooltip text for equipments are colored based on existing text. See below screenshots:
![image](https://user-images.githubusercontent.com/5632219/173452941-91a1050c-91fc-4846-9cfe-b607b98eacfd.png)
![image](https://user-images.githubusercontent.com/5632219/173452974-73d21c34-592f-4414-8f1e-b889719f1721.png)
![image](https://user-images.githubusercontent.com/5632219/173476658-c4c2d54e-8e0b-41c5-a304-382e9d4f84bb.png)

**Comment by Critical-Impact** [comment]
Yeah it's because I'm hijacking the level text as some items lack a description for me to use when altering the tooltip. I'll see what I can do to stop using the colours that the level text does.
