### ISSUE TITLE
Columns for "Favorite" and "Wishlist"

### ISSUE THREAD

**Issue by SkepticSpoon** [Critical-Impact/InventoryTools#92]
Hi. An idea I had while using the plugin, but I don't know if it fits its scope.

Would it be possible to add two new columns: one to mark items as "Favorite" and another to mark them as "Wishlist"? The columns would have a checkmark we could tick and then we could filter by them like we do with any other column

**Comment by Critical-Impact** [comment]
So I can do this though on caveat I would like your thoughts on, basically I don't track where items move to so if I were to make a favourite/wishlist if you favourited a specific item it'd favourite that entire group of items.
It might be possible to favourite items with specific load outs(materia, etc) but if you had 2 items with exactly the same materia/hq status it'd display both if you favourited one.
Do you think that'd be a problem?

**Comment by SkepticSpoon** [comment]
Just to make sure I understand, what do you mean with "entire group of items"?

Is it if I favorite a piece of gear or an item that same piece/item would be favorited across all the locations and all versions of that item (NQ/HQ, different materia, etc) would get favorited as well?

If that's what you mean, for my use case that would not be a problem whatsoever. It would still be a life saver.

Also, favoriting and/or wishlisting an item, would it get favorited/wishlisted across all filters/searches, or would it be filter/search specific? If both are possible, I guess the best would be a setting to choose if we want the favorites and the wishlist to be filter/search specific or across all the filters/searches. But if only one of this cases is possible within the plugin capabilities either one would still be immensely useful for me

If it helps , what I'd use this for would be to mark pieces of gear or items I like/use very much/want to use in something (glamour, recipe, etc) as favorites (the favorite filter) and mark gear/items I want to get/buy (wishlist filter)

**Comment by SkepticSpoon** [comment]
Also, sorry for the slightly off topic but I don't know how to message you other way. I'm still a noob at github and plugin suggestions and I don't want to break etiquette/spam.

I have a few more random suggestions. Should I open an issue for each one? Should I group them (filters, UI, ...)? Should I open an issue for all of them at the same time?

Also, can I suggest filters/features that are present in other plugins but would be useful to have in Allagan Tools so that I don't have to make the same search in more than one plugin? The other day in the goat discord someone replied saying plugins don't usually replicate functions of other plugins, so I just want to make sure that these types of suggestions are acceptable

**Comment by SkepticSpoon** [comment]
Hi again. An alternative idea to the Favorite and Wishlist I proposed that I had while experimenting with the new Craft Lists. Maybe this system of lists could be expanded to make it possible to add any kind of item (craftable or not) and then we could make any list we want, like a favorite items list, a wishlist, a list of items to buy when we go to other world/datacenter, a list of glamour items that go together well... Anything the player might find useful, the possibilities are endless

Then in the Search Filters a new column could be added, called "Lists" or something, and if the item is added to any list, that column will show the names of the lists the item is added to. 

I don't know if this is easier or more difficult from a coding/development standpoint for you, but I just thought it allowed more flexibility and maybe could make use of a system you are already actively developing.

Either way you think is better, anyone of these two alternatives (either the original proposal of a Favorite and a Wishlist marker or this List system) would be useful IMHO

**Comment by Critical-Impact** [comment]
Definitely split them up into multiple issues if you can :)
I don't take any issue with plugins implementing the same features, I think anything I make will be fairly tightly integrated with the rest of my plugin so I don't see huge overlap

I do like the idea of generic lists, will need to mockup some ideas of the interface though the systems are in place for having many different types of lists/filters and I plan on making more in the future.

Not sure which I prefer favourite/wishlist vs lists but I'll have a think, might end up being both, can't really say at this point

With 6.2 fast approaching it might break a bunch of stuff so holding on for that before I begin work on new features.

**Comment by SkepticSpoon** [comment]
Sure thing, I was expecting you would be waiting for after 6.2, it makes sense :) Then as soon as I can I'll start posting the ideas I've been having into multiple issues, even if they're not possible, it might give you ideas for other things at least :D

**Comment by Critical-Impact** [comment]
Marking this as done, we now have favourites and curated lists
