### ISSUE TITLE
Massive tooltip overlasys popping when mouse hovering items

### ISSUE THREAD

**Issue by qohqoh** [Critical-Impact/InventoryTools#94]
I got Massive tooltip overlasys popping when mouse hovering items
[20:23] Overlays refreshing, active filter is no filter
[20:23] Overlays refreshing, active filter is no filter
![image](https://user-images.githubusercontent.com/107040809/183900789-e552aea3-6348-410c-8e1d-e9d4c02e057b.png)

**Comment by Critical-Impact** [comment]
Can you show me a screenshot of it happening? As far as I can see that is screenshots of item windows
I think I know what it is and I plan on adding limits to the number of items that can be shown in the tooltips

**Comment by qohqoh** [comment]
it non-stopping popping the item info overlay when I mouseover an item 
![ffxiv_08102022_203705_468](https://user-images.githubusercontent.com/107040809/183903280-c6a5a71c-eb77-4450-abdc-53c0d7d60aba.png)

**Comment by qohqoh** [comment]
sorry not got the overlay
![image](https://user-images.githubusercontent.com/107040809/183903756-0ffe00ad-b6c1-4c41-8b25-2414615dc912.png)

**Comment by qohqoh** [comment]
https://user-images.githubusercontent.com/107040809/183906567-a5eac156-e6de-4226-bbcb-cae3d23aa7cb.mp4

**Comment by Critical-Impact** [comment]
Are you sure you didn't type in /atlogging ?
If you turn on chat logging you'll see those messages
Chat logging is mostly for debugging so if you type in /atlogging it should stop those messages from coming up.

**Comment by qohqoh** [comment]
yes I open itlogging just want to know what's happening 
actually I don't know how to toggle off the info overlay

**Comment by Critical-Impact** [comment]
Closing this, /atlogging was removed, it's a debug function and should not have been included.
