### ISSUE TITLE
Issue with Craft List Tracking

### ISSUE THREAD

**Issue by SubaruYashiro** [Critical-Impact/InventoryTools#96]
- You can't gather Upland Wheat Flour, only from crafting (Pic 1)
- At least from testing Rarefied Giant Popoto Pancakes, the Gather/Buy from the list is missing some items (Gianthive Chip, and Upland Wheat)
- It Seems that there's some Tracking Issue for Gathering Item (Not sure what causes it), but it immediately changed into Done when i get the required amount. It also sometimes change the Status (Need 162, I have 121, but it says Retrieve 123, At first it was Retrieve 162 (I actually have a lot of the material in the retainer for this craft))
- Pre-Craft Tracking at first was working perfectly, Tracking 1 by 1 until it's done, but the 2nd time i do craft the pre-craft, it didn't track the pre-craft at all until i finish crafting, which change the status to Done
![image](https://user-images.githubusercontent.com/96951106/184283757-e59a342d-0ec7-40fc-a8e2-bb1b8fca3f85.png)

**Comment by Critical-Impact** [comment]
There was an issue with the way I was drawing the individual sections which was causing some of the tables to render weirdly which might account for some of the issues you were seeing.
I haven't pushed anything to testing yet but once I do can you give this another go and see if you run into any issues.

**Comment by Critical-Impact** [comment]
Closing this, let me know if you still run into issues
