### ISSUE TITLE
[Suggestion] Drop sources from item info window

### ISSUE THREAD

**Issue by razk3v** [Critical-Impact/InventoryTools#97]
Hi! I started this issue first to suggest a way to see more info about an item, example: recipes, source: if buyable, then from who and where, if gatherable, the same, and if droppable, the same thing. Then I noticed another issue in this repository and also noticed the existence of a testing build. I've now learned how to set that up and I've found that you updated (and even nicely rebranded) the plugin, and added that item info window! It's reaaally good, I really really like it, and I thank you so much for developing that.
My main suggestion here is to add drop sources, as an example, Coeurl Skin shows no source, and Wolf Fang does show a source but it is "Venture". I'm fully aware that this is experimental yet and you plan on developing these features, but I guess it's not a bad thing to suggest anyway =)
Those drop sources could be all the actual monster sources (example, all the coeurls or wolves that drop those respective materials, their level and their location), but in the case of a, say, weapon, it could say "Sastasha (Hard) Lv.50" (if it's a global sastasha hard drop) or something like that. Thanks!

**Comment by Critical-Impact** [comment]
Drops/Chests are not actually stored within the game data so it's harder, I am working on a library to parse the supplemental data from various online sources and load it in. It'll take some time before it's done but there's some preliminary work done in https://github.com/Critical-Impact/LuminaSupplemental that this plugin will use for calculating the sources of items.

**Comment by Critical-Impact** [comment]
Most of the information I can pull from external sources is now integrated. There are still a few things missing but I will slowly work towards filling those blanks in.
Closing this as I'd say the ticket is mostly fulfilled
